### ISSUE TITLE
inconsistent calculation of metrics

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1193]
data: 20170307_issue1193/

The two following commands should give the same results, but they don't:
~~~
sct_extract_metric -i 001E_datapet_1mm.nii.gz -f PAM50_levels_BIN_T11-T12.nii.gz -method bin
~~~
--> 0, PAM50_levels_BIN_T11-T12.nii.gz [2299.0]:    1.14379832948 +/- 0.782535141076

~~~
sct_extract_metric -i 001E_datapet_1mm.nii.gz -f label/template -l 3 -vert 18:19 -method bin
~~~
--> 3, spinal cord [2328.0]:    1.13402642788 +/- 0.782505806446

**Comment by slevyrosetti** [comment]
This difference might me due to few voxels of a slice in-between T10 and T11 that are included in your mask but that belong to a slice in majority at T10. The vertebral level selection in `sct_extract_metric` is performed slice-wise because it cannot be voxel-wise (e.g., when the registration of the vertebral labeling is not perfect, voxels outside the cord would be included in the estimation).

**Comment by jcohenadad** [comment]
ok i understand. But this is a problem, because ideally atlas-voxels should be selected on the basis of their inclusion in vertebral levels specified by the user. I.e., the result of extract metric should not be affected by the orthogonality of the cord to the slice. Since we have all the info, we should be able to address it properly. I think it's only a matter of computing a mask based on the vertebral_level, and then using this mask to keep only specific voxels in the atlas.

**Comment by slevyrosetti** [comment]
The problem comes from the partial voluming labels: using a binary mask (here, the mask computed based on the selected vertebral levels) removes all the interest of the partial voluming atlas. Moreover, in case of misregistration of the vertebral labeling (which is often the case because it is binary), we would remove lots of "relevant" metric voxels. The question is how to choose the voxels which belong to a specific level (in case of partial voluming labels or misregistration of the vertebral labeling).

I've just though about a solution:
The problem actually comes from the original definition of the vertebral levels in the template space, which is only in the cord. If the vertebral levels were defined in the template space in the entire slice (in the template space), i.e. one vertebral level value for the whole slice (not only in the cord), the problem would be fixed. The warping of the vertebral labeling file would define the voxels to select for a specific level, even in case of misregistration.

**Comment by jcohenadad** [comment]
agreed-- let's leave it for futur dev with medium priority.

**Comment by jcohenadad** [comment]
Isolated case. Closing for now.
