### ISSUE TITLE
Improve error handling when running a pipeline.

### ISSUE THREAD

**Issue by peristeri** [neuropoly/spinalcordtoolbox#1349]
### Description

Right now, the error are display in the stdout. But this fails when running in batch mode on HPC because the stdout is not available.

One of the solution is to log the errors separately from the information generated by the application

**Comment by peristeri** [comment]
This issue is a subset to #1475

**Comment by joshuacwnewton** [comment]
Some comments:
* `sct_pipeline` is no longer used, and was replaced by `sct_run_batch`
* `sct_run_batch` logs errors in log files.

https://github.com/neuropoly/spinalcordtoolbox/blob/cab82fd13425515a8568225dbe7fc003d9be2b1f/scripts/sct_run_batch.py#L195-L200

So, I think this issue is no longer relevant. Closing.
