### ISSUE TITLE
Function to analyse lesions

### ISSUE THREAD

**Issue by SaraDupont** [neuropoly/spinalcordtoolbox#1351]
### Description
`sct_analyze_lesions`
This function will provide tools to analyze lesions, such as count of lesions, volume of each lesion, volume of lesions relative to the SC volume, distribution of lesions across vertebral levels.  

### Output 
- Tables of results in several formats: excel, pickle, text, mat
- a nifti file with each lesions labelled 

### Usage
`sct_analyze_lesions -i image_lesion_manual.nii.gz -t path_to_template -ofolder output_folder ` 

optional flags: `-z  4:12 -vert 1:3 -text texture_file_energy.nii.gz,texture_file_correlation.nii.gz`

### To discuss
- How to take into account the vertebral levels ?
- how to output the GM vs WM involvement ?
- how to include the texture analysis ? --> with an additional flag that takes a list of texture maps ?
- individual optional flags (`-z -vert -text`)  or a `-param` flag that include all that ?

### Additional information
--> use same module as in `sct_extract_metric` for extraction of information by vertebral level / by slice

**Comment by charleygros** [comment]
## Usage
```
DESCRIPTION
Extraction of measures from a lesion mask for each lesion:
  - volume [mm^3]
  - si_length [mm]: length along the Superior-to-Inferior axis
  - ax_nominal_diameter [mm]: nominal diameter in the axial cross-sectional plane
  If a reference image (eg gray scale image, texture image) is provided, it computes the averaged 
    value of this image within each lesion.
  If a registered template is provided, it computes the proportion of lesion in (1) each vertebral 
    level, (2) GM and WM (3) ... compared to the total lesion load.

USAGE
sct_analyze_lesion -lesion <file>

MANDATORY ARGUMENTS
 -lesion <file>               Lesion mask to analyze        

OPTIONAL ARGUMENTS
 -sc <file>                   Spinal cord centerline or segmentation file for angle correction of 
                              volume measures
 -im <file>                   Reference image (eg gray scale image, texture image) for extraction 
                              of averaged values within lesions
 -t <str>                     Path to folder containing the atlas/template registered to the 
                              anatomical image Default value = ./label
 -ofolder <folder_creation>   Output folder Default value = ./
 -r {0,1}                     Remove temporary files. Default value = 1
 -v {0,1,2}                   Verbose: 0 = nothing, 1 = classic, 2 = expended Default value = 1
```

## Outputs

**Example of command line:**
![screen shot 2017-06-21 at 9 50 06 am](https://user-images.githubusercontent.com/14353425/27387723-81eab76c-5667-11e7-8ce6-38a629c3a904.png)

**Note**: If the SC segmentation is provided, the measures of volumes are corrected taking account of the angle as done in `sct_process_segmentation`.

- A niifti file (`t2s_sup_lesion_manual_label.nii.gz`) where each lesion has a different label (to refer with the measures):
![screen shot 2017-06-21 at 9 38 07 am](https://user-images.githubusercontent.com/14353425/27387391-9c6f838e-5666-11e7-8e7d-82a2ae87db88.png)

- An excel and a pickle (`t2s_sup_lesion_manual_analysis.xlsx`) containing the measures:
![screen shot 2017-06-21 at 9 57 44 am](https://user-images.githubusercontent.com/14353425/27388037-4ed3881c-5668-11e7-98cf-1dc67217fcd0.png)

1. `label`: value of the lesion in the file `t2s_sup_lesion_manual_label.nii.gz`
2. `volume`: volume of each lesion in mm^3
3. `si_length`: length of the lesion along the superior-to-inferior axis in mm
4. `ax_nominal_diameter`: nominal diameter in the axial cross-sectional plane in mm
5. `mean_t2s_sup`: (if the file `t2s_sup.nii.gz` is provided with the flag `-im`) mean value (ie intensity) within each lesion
6. `std_t2s_sup`: (if the file `t2s_sup.nii.gz` is provided with the flag `-im`) standard deviation value (ie intensity) within each lesion
7. `Ci`: (if the folder `/label` is provided with the flag `-t`) for each lesion: ratio between the volume of lesion_#i in the current vertebral level AND the total volume of the lesion_#i.
8. `GM`: (if the folder `/label` is provided with the flag `-t`) for each lesion: ratio between the volume of lesion_#i in the GM (`PAM50_gm.nii.gz`, with threshold=0.5) AND the total volume of the lesion_#i.
9. `WM`: (if the folder `/label` is provided with the flag `-t`) for each lesion: ratio between the volume of lesion_#i in the WM (`PAM50_wm.nii.gz`, with threshold=0.5) AND the total volume of the lesion_#i.

## Terminal Output
```
Check folder existence...

Create temporary folder...

Label connected regions of the masked image...

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Computing physical coordinates of centerline/segmentation...
.. Smoothing algo = hanning
.. Windows length = 80
WARNING: The smoothing window is larger than the number of points. New value: 16
WARNING: The smoothing window is larger than the number of points. New value: 16

Measures on lesion #1...
  Volume : 54.74 mm^3
  (S-I) length : 2.45 mm
  Max. axial nominal diameter : 1.74 mm
  Proportion of lesion #1 in vertebrae... 
    - C3 : 21.62 % (11.84 mm^3)
    - C4 : 78.38 % (42.9 mm^3)
  Proportion of lesion #1 in GM : 21.85 % (11.96 mm^3)
  Proportion of lesion #1 in WM : 77.25 % (42.29 mm^3)

Measures on lesion #2...
  Volume : 12.83 mm^3
  (S-I) length : 0.7 mm
  Max. axial nominal diameter : 1.23 mm
  Proportion of lesion #2 in vertebrae... 
    - C2 : 100.0 % (12.83 mm^3)
  Proportion of lesion #2 in GM : 0.0 % (0.0 mm^3)
  Proportion of lesion #2 in WM : 99.04 % (12.71 mm^3)

Measures on lesion #3...
  Volume : 83.13 mm^3
  (S-I) length : 4.21 mm
  Max. axial nominal diameter : 1.73 mm
  Proportion of lesion #3 in vertebrae... 
    - C2 : 20.48 % (17.03 mm^3)
    - C3 : 54.75 % (45.51 mm^3)
    - C4 : 24.77 % (20.59 mm^3)
  Proportion of lesion #3 in GM : 3.12 % (2.59 mm^3)
  Proportion of lesion #3 in WM : 96.88 % (80.54 mm^3)

Measures on lesion #4...
  Volume : 32.18 mm^3
  (S-I) length : 1.75 mm
  Max. axial nominal diameter : 1.77 mm
  Proportion of lesion #4 in vertebrae... 
    - C3 : 63.61 % (20.47 mm^3)
    - C4 : 32.56 % (10.48 mm^3)
  Proportion of lesion #4 in GM : 13.03 % (4.19 mm^3)
  Proportion of lesion #4 in WM : 81.99 % (26.38 mm^3)

Measures on lesion #5...
  Volume : 2.59 mm^3
  (S-I) length : 0.35 mm
  Max. axial nominal diameter : 0.77 mm
  Proportion of lesion #5 in vertebrae... 
    - C4 : 100.0 % (2.59 mm^3)
  Proportion of lesion #5 in GM : 0.0 % (0.0 mm^3)
  Proportion of lesion #5 in WM : 95.24 % (2.47 mm^3)

Measures on lesion #6...
  Volume : 3.95 mm^3
  (S-I) length : 0.7 mm
  Max. axial nominal diameter : 0.71 mm
  Proportion of lesion #6 in vertebrae... 
    - C3 : 81.25 % (3.21 mm^3)
  Proportion of lesion #6 in GM : 0.0 % (0.0 mm^3)
  Proportion of lesion #6 in WM : 62.5 % (2.47 mm^3)

Compute reference image features...
Mean+/-std of lesion #1 in t2s_sup file: 667.66+/-51.2
Mean+/-std of lesion #2 in t2s_sup file: 711.4+/-37.05
Mean+/-std of lesion #3 in t2s_sup file: 707.64+/-67.7
Mean+/-std of lesion #4 in t2s_sup file: 695.99+/-55.48
Mean+/-std of lesion #5 in t2s_sup file: 587.9+/-22.56
Mean+/-std of lesion #6 in t2s_sup file: 690.88+/-40.45

Averaged measures...
  Volume = 31.57+/-29.3 mm^3
  (S-I) Length = 1.7+/-1.33 mm
  Nominal Diameter = 1.32+/-0.45 mm
  Proportion of lesions in WM / GM = 85.48% / 6.33%

Total volume = 189.41 mm^3
Lesion count = 6

Save results files...

Done! To view the labeled lesion file (one value per lesion), type:
fslview /Users/chgroc/data/i1351/rennes_20170112_34/t2s_sup/t2s_sup.nii.gz /Users/chgroc/data/i1351/rennes_20170112_34/t2s_sup/t2s_sup_lesion_manual_label.nii.gz -l Red-Yellow -t 0.7 & 
```

## To discuss
1. If the registration did not work perfectly, it results in incoherent results for the vertebral analysis, example for lesion#6 above:
```
   label C1 [%]      C2 [%]     C3 [%]      C4 [%]
      6      0.0    0.000000  81.249791    0.000000 
```
--> the sum should equal 100% but because some voxels of this little lesion are outside the `PAM50_levels.nii.gz` file it results in incoherent results
(we thought about some solutions to address this issue --> let's discuss that in sct_meeting if possible)

2. Deal with the partial volume effect --> would allow to do the analysis for the WM tracts

Any comments/suggestion?

(Merci à Sara et Benjamin pour leur aide précieuse!)

**Comment by charleygros** [comment]
Changes (related to discussions during sct_meeting):
- "Lesion count=XX" --> displayed at the beginning in the terminal
- Warning message in the Terminal when the proportion of lesion in each region (e.g., WM and GM) does not sum up to 100%
- Angle correction only for length and diameter computation (not for volume computation)
- si_length --> length and "ax_nominal_diameter" --> "max_equivalent_diameter"

**Comment by charleygros** [comment]
@jcohenadad : Concerning the measure "volume of ROI impacted by lesion divided by the total ROI volume": In meeting you said that you would like to refactor `sct_extract_metrics` to make it compatible with `sct_analyze_lesion` to take into account the PVE for measurements on lesions-mask.

But for Dominique's Project, we need that measure (with PVE method `weighted average`) --> I was thinking of implementing this function. We could call it into `sct_analyze_lesion` temporarily --> allow us to do Dominique project without duplication of code.
And when you will refactor `sct_extract_metrics` --> we will call your functions instead of the one described just above (which is temporarily, to allow Dominique to continue).

What is your feeling on that?

**Comment by jcohenadad** [comment]
my feeling is good, thanks. Sorry i didn't have the time to work on refactoring extract_metric

**Comment by charleygros** [comment]
First version:
```python
def relative_ROIvol_in_mask(im_mask, im_atlas_roi, im_template_vert=None, vert_level=None, verbose=1):
  #
  #   Goal:
  #         This function computes the percentage of ROI occupied by binary mask
  #         --> ie volume of the intersection between {im_mask and im_roi} divided by the volume of roi
  #         If im_template_vert and vert are specified, the ROI is restricted to the given vert_level
  #         The PVE is handled by the method 'weighted_average'
  #
  #   Inputs:
  #           - im_mask - type=Image - binary mask (eg lesions)
  #           - im_atlas_roi - type=Image - ROI in the same space as im_mask
  #           - im_template_vert - type=Image - vertebral template in the same space as im_mask
  #           - vert_level - type=int - vertebral level ID to restrict the ROI
  #           - verbose
  #
```

Example:
```
ROI=WM - vert=3
	Total volume of ROI = 415.07 mm^3
	Volume of im_mask in ROI = 21.15 mm^3
	Percentage of ROI occupied by im_mask = 5.0%
```

@jcohenadad : For Dominique's Project, we can work on this branch (the one related to this issue: cg_i1351) to use this function, this is perfectly feasible. Or do you prefer to do a pull request?

**Comment by charleygros** [comment]
Need to be discussed:

Suggestion: The output excel has several sheets:
![screen shot 2017-07-27 at 7 46 03 pm](https://user-images.githubusercontent.com/14353425/28696636-bc0acda6-7304-11e7-94e3-195f30973aed.png)
... the names of the sheets need to be improved :/

### 1. measures:
![screen shot 2017-07-27 at 7 45 47 pm](https://user-images.githubusercontent.com/14353425/28696642-c5f12838-7304-11e7-9653-01617f18806c.png)

As discussed in meeting:
- volume: volume of each lesion in mm^3
- length: length along the Superior-Inferior axis
- max_equivalent_diameter: maximum diameter of the lesion, when approximating the lesion as a circle in the axial cross-sectional plane orthogonal to the spinal cord
- mean_t2s_sup: (if the file t2s_sup.nii.gz is provided with the flag -im) mean value (ie intensity) within each lesion
- std_t2s_sup: (if the file t2s_sup.nii.gz is provided with the flag -im) standard deviation value (ie intensity) within each lesion

### 2. ROI_occupied_by_lesion:
![screen shot 2017-07-27 at 7 52 58 pm](https://user-images.githubusercontent.com/14353425/28696712-39713550-7305-11e7-90a1-cfb8503095e6.png)
Interpretation:
Cell[4 ; C] --> 24% of the WM of C3 is occupied by lesion
Cell[5 ; J] --> 2% of the PAM50_atlas_03 of C4 is occupied by lesion

### 3. lesion#4_distribution:
![screen shot 2017-07-27 at 7 48 53 pm](https://user-images.githubusercontent.com/14353425/28696747-97734d78-7305-11e7-93f7-141182e8c466.png)
Interpretation:
Cell[4 ; H] --> 4% of the 4th lesion is located in the 6th tract of PAM50 of the C3 vertebral level
Cell[6 ; N] --> 34% of the 4th lesion is located in the 12th tract of PAM50
Cell[5 ; AL] --> 33% of the 4th lesion is located in C4 vertebral level

Any comment is welcome !

**Comment by jcohenadad** [comment]
nice! i would change:
ROI=WM - vert=3 --> ROI=WM, vert=3 (to avoid confusion with subtraction)
