### ISSUE TITLE
Establish a clear SOP for installing SCT offline

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1591]

**Comment by zougloub** [comment]
The methods that have been suggested so far:

- Docker containers:
  - Linux containers can run on Windows since recently.
  - Docker for Windows requires 64bit Windows 10 Pro with Hyper-V available -> possible BIOS access to unlock virtualization feature.
  - Provide Docker Installer and container image, in case of no internet.
- Bootable USB:
  - May need BIOS access (probably "F12" is sufficient on PC).
  - Slow-ish.
- VNC to containers hosted on shared computer:
  - Idea: install SCT on a container, instantiate it many times.
  - Could be a problem if network is really bad.
  - Could be a problem if users want to go home with their production.
- Windows VM installers and VM
  - For the poor souls that run Windows, and in particular the Home flavor
- SCT archives:
  - Idea: Install SCT in containers, and provide archive of ~/sct to users, depending on what they run.
  - Won't work on users who come with bare Windows.

A form of consensus would be:

- Provide a USB key
- Bootable, ready to run
- Also with ~/sct archive for OSX
- Also with ~/sct archive for mainstream distros (eg. ubuntu 16-18 + debian 8-9 + fedora/centos)
- Also with ~/sct archive for rusty distros (eg. debian 7)
- Also with the Windows docker installer
- Also with a container image
- Also with the Windows VM system installer
- Also with a VM image

**Comment by benjamindeleener** [comment]
My feedback on the "VNC to containers hosted on shared computer" solution:
- If no internet connection, we can create a local network using a router, that allows participants to connect via VNC to a guest account on the computer, on which SCT is installed and data are already downloaded. 
- Updating the configuration with a new version of SCT 3 hours before the course is relatively easy, as we only need to update the computer once (install the new version of SCT).
- We can configure and test the computer in Montreal, and bring it to the conference so that we don't need to be stressed about finding a computer, configuring it, installing SCT and the data, all one day before the course.
- To make sure the VNC performance is good, it would be better to have multiple computers with different OS installed.

**Comment by jcohenadad** [comment]
A few considerations:
- people like to do something else on their laptop during the course (check email, facebook, ...), therefore a bootable new environment might be disorienting/scary.
- it would be nice to come up with a solution that would also be applicable "outside" the course environment, as a better time investment from our side. So for example, that would favor the docker vs. the bootable hard drive approach. 
- to me the "VNC to containers hosted on shared computer" seems like a nice backup solution in case something goes wrong, esp. if we can come with a router in case of internet glitch.

**Comment by zougloub** [comment]
@fperdigon did the bootable USB key, it will need to run a tagged version of SCT for the course.

On my end, WIP on preparing (the way to generate) SCT offline archives for linux distros and mac.

**Comment by zougloub** [comment]
There was a https://github.com/neuropoly/sct_docker repo (thanks @poquirion), I'm expanding on it (https://github.com/zougloub/sct_docker/tree/cJ-offline-and-testing) to generate the offline archives as a side effect of having Docker containers for various distros.
Everything was tested on Windows, and now it's pretty clear what to put on a USB key to allow offline installation of Docker and the containers.

For the "VNC" idea, given that VNC can be cumbersome when it comes to keyboard translation and some other things, compared to X11 forwarding, the latter would be preferably used.
I'll see whether a simple script can spawn several containers for different users.

Example of container images: https://hub.docker.com/r/zougloub/neuropoly/tags/

Container dumps are ~ 3 GB per distro (we'd probably choose only one, to be *the* one); offline archives for Linux are ~ 1 GB each. There's ~ 500 MB of Docker install files for Windows.

**Comment by jcohenadad** [comment]
fantastic! thank you so much guys
