### ISSUE TITLE
Handle multiple inputs specified with "*"

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1611]
currently, the following fails:
~~~
sct_image *.nii.gz -concat t -o merged.nii.gz
~~~
Because it is interpreted by the Terminal parser as multiple inputs separated by space:
~~~
Running /Users/julien/code/sct/scripts/sct_image.py t1_sct_004.nii.gz t1_sct_008.nii.gz t1_unf_spinal-MSL_10.nii.gz -concat t -o merged.nii.gz
ERROR: argument t1_sct_004.nii.gz t1_sct_008.nii.gz t1_unf_spinal-MSL_10.nii.gz does not exist. See documentation.
Aborted...
~~~
The current way to do it is to list all input files, separated by a comma, which is a pain:
~~~
sct_image t1_sct_004.nii.gz,t1_sct_008.nii.gz,t1_unf_spinal-MSL_10.nii.gz -concat t -o merged.nii.gz
~~~

@zougloub any idea how to do this properly?

**Comment by zougloub** [comment]
The change you're proposing is breaking the compatibility, but I'd assume that this call is rarely made, which is why you're so "casual" about doing it. There'd be no problem changing the parser to support it.

But I'm currently trying to figure out if the SCT built-in parser can be replaced by the standard `argparse`. This msct_parser is really bothering me (#1548).

**Comment by joshuacwnewton** [comment]
> OK, nothing urgent there, so let's wait and see what the future of msct_parser is going to be

Now that we use `argparse`, this is trivial to do if we use `nargs="+"` (which is space-delimited instead of comma-delimited). 

I had been preserving the comma delimiting for backwards-compatibility purposes, but this would be a good reason to take the plunge and switch. It could be a slight annoyance to users if some arguments use `,` and others use `" "` though.

**Comment by joshuacwnewton** [comment]
> Because it is interpreted by the Terminal parser as multiple inputs separated by space:

I've just noticed that in #2371, `sct_image` was quietly changed to accept multiple inputs using `nargs="+"` which accepts space-delimited arguments (rather than comma-delimited arguments).

This means that using the `*.nii.gz` syntax for `-concat` should work just fine, now.
