### ISSUE TITLE
Proposal/discussion: proper Python API for SCT (vs. subprocesses or calling module.main(args=[...]))

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1621]
Currently SCT is mostly implemented as a command-line API and even the internal calls are working this way.

The code is making heavy use (318 calls) of subprocess calls:
```
     53 scripts/sct_make_ground_truth.py
     48 scripts/sct_register_to_template.py
     40 scripts/sct_register_graymatter.py
     20 scripts/sct_register_multimodal.py
     16 scripts/sct_label_vertebrae.py
     13 scripts/sct_straighten_spinalcord.py
     10 scripts/sct_dmri_eddy_correct.py
      9 scripts/sct_create_mask.py
      9 scripts/sct_convert.py
      8 scripts/msct_smooth.py
      7 scripts/sct_process_segmentation.py
      7 scripts/sct_image.py
      7 scripts/sct_check_dependencies.py
      6 scripts/isct_test_ants.py
      5 scripts/sct_dmri_separate_b0_and_dwi.py
      5 scripts/sct_dmri_moco.py
      5 scripts/msct_moco.py
      4 scripts/sct_smooth_spinalcord.py
      4 scripts/sct_get_centerline.py
      4 scripts/sct_compute_hausdorff_distance.py
      4 scripts/sct_apply_transfo.py
      4 scripts/msct_register.py
      4 scripts/isct_convert_binary_to_trilinear.py
      3 scripts/sct_fmri_moco.py
      3 scripts/sct_flatten_sagittal.py
      3 scripts/sct_dice_coefficient.py
      2 scripts/sct_testing.py
      2 scripts/sct_detect_pmj.py
      2 scripts/sct_crop_image.py
      2 scripts/isct_warpmovie_generator.py
      1 scripts/sct_warp_template.py
      1 scripts/sct_viewer.py
      1 scripts/sct_utils.py
      1 scripts/sct_propseg.py
      1 scripts/sct_pipeline.py
      1 scripts/sct_deepseg_sc.py
      1 scripts/sct_concat_transfo.py
      1 scripts/sct_compute_mtr.py
      1 scripts/msct_image.py
```

A WIP is to create a `main()` function in modules, which is good practice for avoiding `__main__`.
This approach gets rid of one or two subprocess calls (one if `sct.run()` is called with a list (now in #1618), two if it's with a string) and also reduces module loading time, but the syntax is about the same, and we're still reading/writing a ton of temporary files.

A Python API going beyond this `main()` would be very useful:

- Having the processing code in `spinalcordtoolbox` folder/namespace
- Several functions per module
- By using placeholders, functions can take/save file paths, or deal with in-memory contents
- Pass optional hierarchical logger as argument  
  That would allow to have a better graphical understanding of the program flow
- The scripting entry points would be made faster to call since dependencies would be imported on actual execution of the scripting entry point  
  Today calling a program for help can take a while...
```
$ time sct_apply_transfo 
[...]
real    0m1.811s
user    0m1.676s
sys     0m0.131s
```

To proceed with the implementation:

- Start by the most used internal calls (eg. 30 calls to `sct_image -setorient RPI ...`)
- Be really careful about the external API, which will have to last

Some proposals:
- `import spinalcordtoolbox as sct`  
Kind of obvious that we'd want the users to do that. And the internal code would probably use `sctu` for utils.
- `sct.image.reorient(src, dst=None, orientation="RPI")`  
  When `dst is None`, the output data is saved into src. That's kind of like the OpenCV python API.
  Parameters are given meaningful parameters and defaults according to the most common use cases.
- `sct.maths.binarize(src, dst=None, threshold=None, method="fixed")`  
  Function names to make a little more sense.  
  For binarization/thresholding/etc, could try to stay close to existing APIs, and could also put methods like otsu/otsu_adap/otsu_median to get the threshold automagically.
- `sct.image.crop(src, dst=None, spec=(2, 1, -1))`  
  `sct.image.crop(src, dst=None, spec=[(0, 1, -1), (2, 1, -1)])`  
  Could use a cropping specification: cropping could happen on different dimensions at once.
- `sct.transfo.warp(src, dst=None, warping_field=None, interpolation="nn")`
- `sct.transfo.concatenate(src=None, dst=None, transforms=list())`  
- `sct.gm.segment(src, dst=None, method="fast", method_kw=None)` 
  In relation with the discussion about pluggable methods to do the same thing...  
  `sct.gm.segment_deepseg(src, dst=None, ...)` 
  Which users could also call.
  Note that `spinalcordtoolbox.deepseg_gm.deepseg_gm.segment_file()` call is probably not consistent with anything we could come up with.
- Supporting long file names or filenames with spaces when using the Python API. There's no reason why it wouldn't work.

**Comment by zougloub** [comment]
Some effort had been made on NIFTI resample before (#1537), linking issue.

**Comment by jcohenadad** [comment]
Excellent initiative. One thing that needs to be harmonized in SCT is the type of input/output for image data. Currently we have the following:
- file name (sometimes absolute path, sometimes relative)
- nibabel object
- `msct_image` object (SCT-custom image object, based on nibabel, but with additional useful classes, for example: optimize image type before saving, coordinate class which is useful in SCT, etc.).
- numpy matrix (bad idea because we loose header information)

I would go with `msct_image`.

**Comment by jcohenadad** [comment]
@benjamindeleener @charleygros your inputs would be appreciated

**Comment by perone** [comment]
I think that @peristeri started to do that in the past, so probably a conversation with him would be nice given that he probably had an idea in mind. Besides that, some remarks:

- The `Image` class that we have today (from the `msct_image` module) has some memory issues (see #1316). Since this is used everywhere, I think that fixing this should be priority before doing the other changes (today, if you just need a slice from a volume with 4000 slices, all slices will be loaded in memory, which is quite inefficient);

- The mentioned `segment_file()` from `deepseg_gm`, if you look at the function, it is just a wrapper around the `segment_volume()` which is the actual API that receives an in-memory nifti volume. The `segment_file()` is just a convenient function for the command-line wrapper, which can or cannot be exposed as final API, but the `segment_volume()` is actually the API that is supposed to be exposed, and this API does actually use in-memory structure. This is the same pattern that was used in #1537. In my opinion, **both an in-memory object-based and a file-based API are useful for users**, and given that we already need to implement the file-based API for the command-line tools, there is no reason to hide it from final users since we don't really know all their needs. It seems better to let them chose what they need instead of us choosing what we think they need;

- I think that instead of doing efforts to fix the subprocess issue with `main()` approach, it would make more sense to do the refactoring to create the actual APIs like in #1537, since you'll have to refactor again the `main()` changes when you'll be doing the final goal of building an actual API. Doing the changes in the `main()` now will make things a little faster, but it will require refactoring it again in the future, right ?

**Comment by jcohenadad** [comment]
i agree with @perone's approach, both in terms of setting up priorities and also about having APIs both with file name and Image object inputs. If we go that route, we should probably standardize our API names (e.g., `ACTION_image`, `ACTION_file`) and make sure that the `ACTION_image` always refers to the same Image object (from `msct_image`).

**Comment by peristeri** [comment]
Note: The initial attempt to replace all `sct.run` functions with API calls was abandon due to the cyclical dependencies that caused exceptions. Much of the details are forgotten, you can examine the `devel` branch to see where things have gone wrong.

@perone 
Point 1. I agree with the importance of improving the memory consumption of Image. But it is outside the scope of this issue. 
Point 2, you can take it one step further and introduce a FileManagement class that deals efficient use of memory of all images. Again, this is out of scope, but this a good step towards that direction. 
Point 3, I agree, and it should be done strategically.

**Comment by zougloub** [comment]
@perone I was referring to `deepseg_gm` because of the repeat `deepseg_gm.deepseg_gm` in the name, which is kind of weird. Other than that, your code is pretty neat and I agree with your comments.

I propose to list the most widely used internal command-line calls and address them in order, so this discussion progresses.

**Comment by zougloub** [comment]
Not a big fan of systematically creating redundant APIs for `_file` vs `_volume` (or `_image`?) unless there's something to be gained from it (eg. acceleration with paginated access or memory mapping) or the conversion is not straightforward.

**Comment by perone** [comment]
@zougloub what do you mean by redundant ? I'll try to summarize:

1) API with `*_file`: it's a utility wrapper around the `_volume` API. The main point of this function is to expose a file-handling API for the command-line tools or when someone wants to programatically do some action (segment, etc) on a file. This API will do whatever is required at the nifti-level, such as resampling using the header information in the nifti file, etc;

2) API with `*_volume`: works on an in-memory object (which doesn't means that all data is in-memory, due to the `nibabel` caching mechanism). It's the main action, in the `deepseg_gm` case, it will do the segmentation itself;

It's a separation of concerns and I don't see redundancy, they do different things (one is for a file and another one is for an in-memory object). Even if you do not want to expose the `*_file` API, **you'll still need to have that** because you'll have to segment a file from the command-line tool and not an in-memory object (like in the case of the `*_volume` API).

**Comment by zougloub** [comment]
I'm just not a very dogmatic person. Let's say, if you have one-liner functions that do `file_to_volume()` and `volume_to_file()`, you may not have to write the 2 versions of the API for your 3000 functions, when each of them does just that. Of course providing the 2 versions all the time does the extra mile.

**Comment by zougloub** [comment]
To illustrate the idea of code that could work "seamlessly" on things of different types, you can take a look at the `sct.imgproc.binarize()` function [in this sample code](https://github.com/neuropoly/spinalcordtoolbox/blob/cJ-imgproc/spinalcordtoolbox/imgproc.py#L121).

A core function works on an `np.ndarray` and a wrapper takes care of handling the mostly repetitive job of dealing with `Image` or filenames.

**Comment by zougloub** [comment]
I'm going to start working on this, opening a project [here](https://github.com/neuropoly/spinalcordtoolbox/projects/7) with notes (please comment here).

**Comment by jcohenadad** [comment]
i moved the “metrics” under section “in progress” because it is effectively in progress (https://github.com/neuropoly/spinalcordtoolbox/blob/jca/1920-process_seg-csa-perslice/spinalcordtoolbox/metrics.py#L18), however i feel that more discussion is needed. For example, i find there is a large gap between what we call “metrics” as dice/hausdorff, etc. and computed qMRI metrics that are being further processed (averaged across slices, etc.).

**answer from @perone (copied from Slack):**
I was thinking about that, and there is also the difference between a Dice (average slice-wise) and Dice (entire volume). I think we should make a more object-oriented design for these metrics. I was wondering in something like this: an abstraction for applying the metrics in a volume or slice-wise manner and then decoupling the way we apply the metric computation from the metric computation itself. You’ll have a class that would be something like `DiceCoefficient` and then this can be applied both on slice-wise fashion (supporting axial/sag/cor) or volume-wise, but the responsibility of applying this metric would be of another component. Something like:

```volume = nibabel.load(...)
metric = DiceCoefficient(threshold=0.5)

computation = SliceWise(dim="axial", aggregation="mean")
result = computation.compute(volume, metric)```

And the `result` will contain the dice coefficient using a threshold of 0.5, applied slice-wise on the axial axis and aggregated by average. I think that would be very flexible for many metrics but I’m not familiar with all metrics used on SCT so what do you guys think about it ?

**Comment by zougloub** [comment]
I think we can also consider a FP (vs. OOP) option that looks something like:

```python
dice_slicewise = np.mean([dice_coefficient(slice_ref, slice_new) for (slice_ref, slice_new) in Slicer(im_ref, im_new, axis="LR")()])
dice_volume = dice_coefficient(im_ref.data, im_new.data)
```

There may be less code to produce (more 3rd party code to piggy-back onto) and the resulting code can be more straightforward to understand.

**Comment by jcohenadad** [comment]
personally i prefer the FP approach. But one thing that troubles me about the `metrics` module is that there is currently some code to average metrics along slices and/or vertebral levels, implemented [here](https://github.com/neuropoly/spinalcordtoolbox/blob/jca/1920-process_seg-csa-perslice/spinalcordtoolbox/metrics.py#L18). This is quite far from the philosophy of Dice and cie. So, should we rename the currently-implemented module with another name? Or should we refactor it (e.g. remove the csv writing part, etc.). 

Another thing to consider: not all metrics can be computed and then aggregated across slices/levels. For example, `sct_extract_metrics` requires all voxels (all tracts) for estimating metrics using Gaussian mixture modeling (options: -m ml or map). 

Also, `sct_process_segmentation` computes metrics from the segmentation, but this is quite specific to the segmentation world (shape information, centerlines, etc.), which is far from Dice and cie. 

so i think we should stick to the proposed module "metrics" to only deal with distances, and about the current implementation of `average_per_slice_or_level()`, i'm waiting for your comments.

**Comment by zougloub** [comment]
About naming I don't know.  If metrics is a good name for CSA and friends, the module with distances and other statistics could be named 'statistics' or 'statistic'.

Even for statistics, there is stuff you can't aggregate indiscriminately.

About `average_per_slice_or_level()` and your module code, I commented in your ongoing PR.

**Comment by zougloub** [comment]
Relevant comments posted elsewhere:
- https://github.com/neuropoly/spinalcordtoolbox/pull/1931#discussion_r204983562: ground rules for things in the Python API, to raise that new code quality.
- https://github.com/neuropoly/spinalcordtoolbox/pull/1931#discussion_r204984127: accepting `Image` paths or Images by using `Image()` liberal constructor, and returing `Image`s.

**Comment by joshuacwnewton** [comment]
@Drulex Is this issue discussion useful to you at all? Or, have you just been keeping track of the API-ification through the [Project board](https://github.com/neuropoly/spinalcordtoolbox/projects/7)?

**Comment by Drulex** [comment]
> @Drulex I'm wondering if I should close this. Is this issue discussion useful to you at all? Or, have you just been keeping track of the API-ification efforts through the [Project board](https://github.com/neuropoly/spinalcordtoolbox/projects/7) instead?

This issue is linked in the board for reference so I propose to close it. The effort is tackled in chunks (smaller issues) which makes it more manageable, otherwise this issue could stay open for a long while again.
