### ISSUE TITLE
sct_segment_graymatter deprecation

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1622]
With `sct_deepseg_gm`, there are some reasons to deprecate `sct_segment_graymatter` (https://github.com/neuropoly/spinalcordtoolbox/issues/1616#issuecomment-368233124).

Some questions arise:

- Who is using `sct_segment_graymatter`?
- Have they tried  `sct_deepseg_gm` and are they satisfied?
- Should  `sct_segment_graymatter` implementation remain (maintenance burden, eg. #1616) or when should it get phased out?
- Should the `sct_segment_graymatter` front-end remain (the name is not so bad), with a dispatch to different methods from a single compatible entry-point?

**Comment by jcohenadad** [comment]
Few comments/answers to [this](https://github.com/neuropoly/spinalcordtoolbox/issues/1622#issue-299968126):
- Who is using `sct_segment_graymatter`: I would say about 25% of our users, those interested in segmenting the gray matter and use it for (i) improving registration to the template and/or (ii) quantifying qMRI metrics within the GM
- Only a handful of them have tried `sct_deepseg_gm`. I would say that the level of satisfaction varies. For some using T2* contrast, they are usually much more happy than when using `sct_segment_graymatter` (better results). However, for those using non-T2* contrast (e.g., PSIR), they are not happy because the algorithm does not work for these contrasts. @perone could you please comment on the future plan to cover most contrasts our user have? or any plan to mitigate domain adaptation, notably through image preprocessing (e.g., normalization as done in `sct_segment_graymatter`)
- Should `sct_segment_graymatter` implementation remain: I'm really not sure at this point. This will strongly depend on `sct_deepseg_gm`'s ability to surpass `sct_segment_graymatter` for all existing contrasts. So we need @perone's input there.
- Should the `sct_segment_graymatter` front-end remain (the name is not so bad), with a dispatch to different methods from a single compatible entry-point? --> ah! that's something we've been discussing and I think there is no consensus so far. I would be in favour of that, but one strong counter-argument is that the arguments pertaining to each method can be very complex and numerous. Please everyone in SCT team, give your thoughts...

**Comment by perone** [comment]
I think that the natural approach to cover more contrasts now is to work on the unsupervised Domain Adaptation, given that this is also our project for the IVADO grant and it's already in place. My next step is to focus on this soon as possible.

**Comment by jcohenadad** [comment]
Thanks @perone. @benjamindeleener @charleygros your inputs would be appreciated

**Comment by charleygros** [comment]
- Have they tried sct_deepseg_gm and are they satisfied?
I have tried `sct_deepseg_gm` on some data and was really satisfied with it.
I will probably use it on a large cohort of MS patients soon, I will do a follow-up with you guys (only by visual evaluation though since no ground-truth available).

- Should sct_segment_graymatter implementation remain (maintenance burden, eg. #1616) or when should it get phased out?
I would say certainly yes! At least up to the Paris SCT course in June.
One key advantage of `sct_segment_greymatter` is its ability to provide a "realistic" grey matter shape even on very pathological/compressed slices (due to its atlas-based process, which has strong arguments in instances of atrophied cords).

**Comment by jcohenadad** [comment]
won't fix (for now)
