### ISSUE TITLE
Note about output caching

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1625]
Noticed a potential risk in output data caching with no check, for instance, `sct_label_vertebrae` says:
> “Straightening was already run previously. Copying warping fields”

If for whatever reason, the assumption is incorrect, then will cause issues down the line.
It could happen if:
- the input data file is modified
- several input files exist within the same source directory
- the user performs a batch processing of input data and didn't look at SCT code
- the input data is not modified but for whatever reason, SCT changes
I'm not sure if the file naming convention used in `sct_example_data` is universally used and would prevent such an issue.

In general a system that caches outputs should ideally come with a reasonable level integrity checking on the input data (eg. file name + timestamp or even file hash, and perhaps function call parameters and code environment... which can all be hashed to a single value stored as a signature in the output file) that has little chance of reusing invalid data.

**Comment by jcohenadad** [comment]
Agreed. This feature was implemented because the benefit (save ~1min of processing time) surpasses the potential risk listed [here](https://github.com/neuropoly/spinalcordtoolbox/issues/1625#issue-300865846).

**Comment by zougloub** [comment]
For now I just changed the message about file reuse, to make it more explicit that an assumption was made.

**Comment by jcohenadad** [comment]
Because of the [recent developments](https://github.com/neuropoly/spinalcordtoolbox/pull/1669#issuecomment-384737822), this issue is now critical and should be addressed. 

One suggestion would be to create a file `straightening.info` at the end of `sct_straighten_spinalcord`, that includes information about the type of straightening that was done (classical vs. new disc-based), so that SCT knows if it should re-do the straightening later in the pipeline (e.g. in `sct_register_to_template`).

**Comment by benjamindeleener** [comment]
I agree with this solution.

**Comment by jcohenadad** [comment]
Fixed by #1719
