### ISSUE TITLE
Numpy and Scipy versions are not displayed in sct_check_dependencies

### ISSUE THREAD

**Issue by fperdigon** [neuropoly/spinalcordtoolbox#1632]
below result partial result when the command sct_check_dependencies is executed, the issues are indicated with arrows (**<---------**)

Check if nipy (0.4.1) is installed..................[OK]
Check if tensorflow (1.3.0) is installed............[OK]
Check if h5py (2.7.0) is installed..................[OK]
Check if distribute2mpi (0.3.1) is installed........[OK]
Check if numpy is installed................[OK]   **<-----------------------------**
Check if scipy is installed................[OK] **<---------------------------**
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened.......................[OK]

**Comment by fperdigon** [comment]
now it looks like:
...
Check if tensorflow (1.3.0) is installed............[OK]
Check if h5py (2.7.0) is installed..................[OK]
Check if distribute2mpi (0.3.1) is installed........[OK]
Check if numpy (1.11.2) is installed................[OK] <------------------------
Check if scipy (0.18.1) is installed................[OK] <------------------------
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
...

**Comment by jcohenadad** [comment]
@fperdigon the reason we do not display `scipy` and `numpy` versions because the purpose of this display is to check that a specific version is installed, as mentioned by @zougloub [here](https://github.com/neuropoly/spinalcordtoolbox/pull/1633/files#r172672985).

in the case of these two libraries, we cannot specify a particular version, because other libraries (e.g. dipy) will upgrade scipy/numpy to a specific version based on their specific requirements.

therefore we can close this issue and the associated [PR](https://github.com/neuropoly/spinalcordtoolbox/pull/1633/files).
