### ISSUE TITLE
Re-ordering of 4th dimension when apply transformation on 4D scans

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1635]
### Description

When applying a transformation on 4D data, the order of the volume is changed between the input and the output.

### Steps to Reproduce

1. get data from there: `sct_testing/issues/20180309_issue1635`
2. run the following:
~~~
sct_image -i b4000.nii.gz -keep-vol 1 -o b4000_T0.nii.gz
sct_apply_transfo -i b4000.nii.gz -w b4000_0GenericAffine.mat -d b4000_T0.nii.gz -o b4000_reg.nii.gz
fsleyes b4000.nii.gz b4000_reg.nii.gz &
~~~
3. notice that the b=0 scan is now at the T=3 position (previously at T=0)

### State of spinalcordtoolbox

commit: f7ebd4620218c7c0763312d58474c7de5a06c49c

**Comment by fperdigon** [comment]
The problem was that the list of files that are received from the glob.glob () function are not sorted [(see in code)](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_apply_transfo.py#L233)
Here is a portion of a debug print output of the script sct_apply_transfo that I added temporarily while I was looking for the bug. 
...
Merge file back...
%%%%%% DEBUG  DEBUG  DEBUG  DEBUG  DEBUG %%%%%%%
Order of elements
['data_reg_T0000.nii', 'data_reg_T0001.nii', 'data_reg_T0004.nii', 'data_reg_T0002.nii', 'data_reg_T0003.nii']
%%%%%% DEBUG  DEBUG  DEBUG  DEBUG  DEBUG %%%%%%%
  WARNING: File b4000_reg.nii.gz already exists. Deleting it...
  File created: b4000_reg.nii.gz
...
