### ISSUE TITLE
Official Docker image for SCT on Docker Hub

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1678]
### Description
Nowadays there is a spinalcoordtoolbox (https://hub.docker.com/r/neurology/spinalcordtoolbox/) which doesn't seem to be maintained by us. It would be nice if we create an official Neuropoly organization there and then create multiple SCT images (for different versions of SCT and the latest stable one), with support for mounted volumes, etc. This is very useful because users can just type something like:
   
~~~
docker run neuropoly/sct:3.1.1
~~~
 
And then they'll have a docker image with let's say Ubuntu and all the tools to run SCT on the data that they want. This will guarantee that the installation will work independently of the distro that they're using and we can maintain it to add the tools we think it's important, etc.

### TODO

- [x] Upload stable release on neuropoly docker organization
- [x] Document on sphinx (related to #1656)

**Comment by zougloub** [comment]
There's an https://github.com/neuropoly/sct_docker repo, so for now I submitted a PR there.
If we want the Sphinx documentation here, perhaps the files should be moved here.

Take a look at https://github.com/neuropoly/sct_docker/pull/2 ; there's an `sct_docker.py` script that can generate Docker images, and a `sct_docker_testing.py` script that abuses the former, in order to perform testing (PoC stage).
`sct_docker.py` doesn't yet have command-line parameters to build and upload to Docker hub, but that could be added.

**Comment by zougloub** [comment]
Merged neuropoly/sct_docker PR; that repo's README documents usage / installation / generation.
