### ISSUE TITLE
Quasi-systematic under-segmentation with sct_deepseg_sc

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1716]
### Description

I've noticed several cord under-segmentations on T1w contrast with `sct_deepseg_sc` when compared to `sct_propseg`. Example below with `sct_019_t1`:

![screen shot 2018-05-23 at 12 49 05](https://user-images.githubusercontent.com/2482071/40402680-fd2c0e70-5e87-11e8-8044-5d1021bac330.png)

Note that I don't observe as much under-segmentation on T2-like contrasts

**Comment by charleygros** [comment]
I am currently investigating this, and I will do a PR in this respect in few days.

In particular, I feel that we should reduce the binary thresholding at the end of the processing:
https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_deepseg_sc.py#L375
--> exploratory experiments seems to encourage 0.1 instead of 0.75.
