### ISSUE TITLE
Issue for sending email in HCP: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1752]
~~~
Sending email...
Traceback (most recent call last):
  File "/home/jcohen/sct/scripts/sct_pipeline.py", line 692, in <module>
    html=True)
  File "/home/jcohen/sct/scripts/sct_utils.py", line 1097, in send_email
    server.sendmail(addr_from, addr_to, text)
    for each in to_addrs:python/lib/python2.7/smtplib.py", line 740, in sendmail--More--(91%)
TypeError: 'NoneType' object is not iterable
~~~

**Comment by zougloub** [comment]
The `-email` argument is error prone, it's easy to get a crash when parameters weren't provided.

Maybe it's better to keep e-mail settings in a config file and not passed as argument, as the command-line (at least on Cedar) is accessible to all users and someone could snoop on the credentials.

**Comment by zougloub** [comment]
`-email` could take a config path file as argument, the config file being key=value... ?

Applied some band-aid for now.

**Comment by joshuacwnewton** [comment]
Closing as the specific details of this issue are outdated. This area of the codebase has undergone many changes over the years. (`sct_run_batch` replacing `sct_pipeline`, and the addition of `-email-to` and `-email-from` arguments instead of `-email`).

A new issue can be opened if we run into the need for further improvements.
