### ISSUE TITLE
sct_deepseg_sc empty result on data after motion correction

### ISSUE THREAD

**Issue by valosekj** [neuropoly/spinalcordtoolbox#1770]
### Description

Dear SCT experts,
I found out issue with _sct_deepseg_sc_ function when I run it on our data. We have T2 axial DCM patient data which were measured with interleaved sequence. Unfortunately, some of patients moved during examination, so data are corrupted by slice-by-slice motion artifacts.
We created in-house slice-by-slice motion correction script for suppressing this motion artifact (bellow are screenshots of images before and after motion correction). 
When I apply _sct_deepseg_sc_ on both images, in case of motion interrupted data segmentation finish well with satisfactory result, but in case of motion corrected data function finish with error (see below) and segmentation result is empty.
So it looks that our motion correction causes the issue. However, we don´t change image resolution nor 
brightness histogram (see below) of image.

### State of spinalcordtoolbox

Reorienting the segmentation to the original image orientation...
Remove temporary files...
QC: test with Axial slice
Traceback (most recent call last):
  File "/usr/local/lib/sct_3.1.1/python/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/lib/sct_3.1.1/python/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/sct_3.1.1/python/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/lib/sct_3.1.1/python/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file slice.py, line 228

### Additional Information
![t2_tra_with_artifacts](https://user-images.githubusercontent.com/39456460/40353718-7379b234-5db2-11e8-9420-84f7118c722e.png)
![t2_tra_slice_corrected](https://user-images.githubusercontent.com/39456460/40353720-761fb376-5db2-11e8-80e9-3fad70f450e3.png)
![t2_tra_histograms](https://user-images.githubusercontent.com/39456460/40353728-79581ff6-5db2-11e8-8b33-b9ddd0bd3d55.png)

**Comment by jcohenadad** [comment]
Does your motion correction code output an image with a different output type? I feel that we are back to [this issue](https://github.com/neuropoly/spinalcordtoolbox/issues/1740#issuecomment-390974859). If that's the case, could you try the "x1000" trick and let us know how it goes?

Note: the error you are seeing (`TypeError: not all arguments converted during string formatting`) is generated by the QC module (because there is no visible segmentation).

**Comment by valosekj** [comment]
Our motion correction code has on output image with same data type (float32).
In this case we are working with original data before normalization. You can see at histogram that we have values of brightness between 0 and approx. 750 (histogram curves for both images look almost same).
And I am attaching a screenshot which illustrates that segmentation works fine on image before motion correction (picture below).
![t2_tra_seg](https://user-images.githubusercontent.com/39456460/40373980-660536ce-5de8-11e8-9135-24a38aae392e.png)

**Comment by jcohenadad** [comment]
I am really puzzled. @valosekj would you mind sending me the motion corrected data in private message? We'll investigate. Thanks!

**Comment by jcohenadad** [comment]
This issue is related to the presence of NaN in the slice=0 of the motion-corrected image:
![screen shot 2018-05-23 at 15 52 30](https://user-images.githubusercontent.com/2482071/40408244-d6068284-5ea1-11e8-958a-9c248f6eff4e.png)

An issue has been opened to inform user when that happens (#1774).

Since the NaNs are only in slice=0, a workaround for this image is to remove the NaN-slice and run `sct_deepseg_sc`:
~~~
sct_crop_image -i 2060B_03s_t2_me2d_tra_p2_slice_corrected.nii.gz -dim 2 -start 1 -end -1 -o 2060B_03s_t2_me2d_tra_p2_slice_corrected_crop.nii.gz
sct_deepseg_sc -i 2060B_03s_t2_me2d_tra_p2_slice_corrected_crop.nii.gz -c t2
~~~

**Comment by valosekj** [comment]
Thank you very much for your help Julien and sorry for our inattention about the first missing slice (this was caused by issue in our slice correction function). We fixed our slice correction function and now segmentation works properly.
