### ISSUE TITLE
No fslview subcortical colormap in display_viewer_syntax()

### ISSUE THREAD

**Issue by MelaniePelegrini** [neuropoly/spinalcordtoolbox#1871]
Hello,

I've just installed SCT release 3.2.1 in the Debian VirtualMachine (Windows host). When trying
$SCT_DIR/batch_processing.sh, I get the following error:

Sucessfully generated the QC results in /home/brain/qc_batch_processing/qc_results.json
Use the following command to see the results in a browser:
xdg-open "/home/brain/qc_batch_processing/index.html"
Traceback (most recent call last):
  File "/home/brain/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 957, in <module>
    main()
  File "/home/brain/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 363, in main
    sct.display_viewer_syntax([fname_in, fname_seg_labeled], colormaps=['', 'subcortical'], opacities=['1', '0.5'])
  File "/home/brain/spinalcordtoolbox/scripts/sct_utils.py", line 523, in display_viewer_syntax
    cmd += ' -l ' + dict_fslview[colormaps[i]]
KeyError: 'subcortical'

Any help will be welcome ;-)
Melanie

**Comment by jcohenadad** [comment]
Hi Mélanie,
Thank you for the feedback. The issue is related to the recent change of default colormap, compatible with fsleyes, but not with fslview (which is running on this VM). Sorry for the oversight. For now you can ignore this issue though, because it is not affecting the process. It is only related to a bug while displaying verbose on the terminal.

**Comment by MelaniePelegrini** [comment]
Thanks so much for the workaround, I installed fsleyes, the batch works now :-D.
