### ISSUE TITLE
Naming conventions for branches

### ISSUE THREAD

**Issue by abtahizadeh** [neuropoly/spinalcordtoolbox#1885]
### Prerequisites

* [ *] Did you check past issues for similar issue(s) ?
* [ ] Can you reproduce the issue with any of the files found in `sct_testing_data` ?
* [ ] If you are using a development environment, is your environment updated ?

### Description

To have a unified naming convention for branches.
Ref: https://stackoverflow.com/a/6065944

### Steps to Reproduce

1. [First Step]
Agree on format/title/grouping of branches
2. [Second Step]
Update guidelines
3. [and so on...]
Follow the rules of the naming convention from now on ....!

**Expected behavior:**

Easily trackable branches

### Additional Information

Plz share your thoughts

**Comment by jcohenadad** [comment]
@abtahizadeh [https://stackoverflow.com/a/6065944](this link) looks more like a discussion to me-- can you plz summarize what you propose and then i'll comment-- thx

**Comment by abtahizadeh** [comment]
Something like:

_FORMAT                         |    Example_
`feature/[Issue#]`         |    feature/1885
`release/[version_id]`   |    release/1.2.3
`test/[Issue#]`               |    test/1572
`hotfix/[Issue#]`            |    hotfix/2761    
`patch/[Issue#]`            |   patch/2617

I did not propose a solution because the purpose of this ticket was to raise the discussion.

**Comment by jcohenadad** [comment]
i like these suggestions, originally we proposed to have the acronym of the person submitting (e.g. jca_issue1892) so that if a student creates a branch and then leaves the lab, it's easier for me to know who created what (therefore, easier to know what to keep/delete). But i guess we can have that info anyway from the initial branch commit...

so i would suggest the following:
- FORMAT | Example | Delete after commit
- `[category]/[Issue#]` | bug/1889 | Yes
- `release/[version#]` | release/3.2.1 | No

where [category] can take the values defined [here](https://github.com/neuropoly/spinalcordtoolbox/wiki/Label-definition#issue-category)

if you find some category names are too long, we can shorten them: installation-->install, documentation-->doc, etc.

note: we don't really use the concept of patch (yet).

**Comment by abtahizadeh** [comment]
I totally agree with your suggestions! Thanks for the quick response, 👍 
if everyone is happy, we can make some rules, document these stuff and act ASAP.

**Comment by perone** [comment]
I would just add new format like `[category]/dev_[any name]` or something like that, just for code we're experimenting as development and that we want to save the code, but that's not related to any issue yet.

**Comment by jcohenadad** [comment]
@abtahizadeh yes, go ahead please. Thanks!

**Comment by abtahizadeh** [comment]
We have new branching conventions in place:
https://github.com/neuropoly/spinalcordtoolbox/wiki/Branching-Conventions

**Comment by jcohenadad** [comment]
@abtahizadeh i moved the wiki page [here](https://github.com/neuropoly/spinalcordtoolbox/wiki/Contribution-Guidelines#naming-your-branch), otherwise it will be missed (the previous page was not referenced anywhere)

**Comment by perone** [comment]
Just a heads up, the Contributing guidelines are here: `https://github.com/neuropoly/spinalcordtoolbox/blob/master/CONTRIBUTING.md`

This is used to add a link on the right side of each issue, so I think that we should move the most updated one to the `CONTRIBUTING.md` file and delete the other to avoid confusion.

**Comment by jcohenadad** [comment]
ah! sh... thank you for pointing this out @perone. i am now painfully trying to resolve conflicts...

**Comment by jcohenadad** [comment]
UPDATE: with the implemented approach, I wanted to create a branch `release/3.2.2` as per our new convention, however i was not able to because the branch `release` already exists. Debate is open...

**Comment by zougloub** [comment]
Sorry I'm seeing that issue only now... here's some of my feedback:

- I don't see a strong rationale to change from the status quo which is to have branches named with a personal identifier and a more-or-less descriptive string, and to submit PR's for master unless told otherwise. Going stricter should serve an obvious purpose / solve obvious issues, because it's more overhead.

- The idea of having branches that must have an issue number is forcing to have issues created beforehands... that kind of stuff, you usually do only because some critical software standard (eg. DO178) mandates you to do it. This is overhead that I don't find necessary.

- Very important: a developer shouldn't have to read the bug tracker of a project in order to understand the code. Commits should have descriptions. I think the idea of adding ``(${action} #${issue_number})`` at the end of commit titles is a sufficient link to the issue tracker, but the commit should clearly state what it does. Bonus: the info gets automagically inserted in the PR text by github, so you can mash it up and create a sexy summary that makes devs want to pull in the PR.  
Also reading `jca_pipelineViolin` is much clearer than `jca_1429`.

- Release branches only make sense for maintenance of major versions, and that's the kind of stuff you create after you need them.
“hey, someone is using 2.4.6 and we're at 3.2.5 but they want that fix... let's branch out and create 2.4.6-z and a 2.4.6.1 for them”

- Some [link about differences between the "flow" scheme mentioned in the SO link above, and the “github” workflow](https://www.slideshare.net/ssuser398894/git-series-episode-3-git-flow-and-githubflow); on SCT the wokflow is github, except for the `release` branch where we're doing some magic with the `version.txt` file. IMO the “flow” workflow adds systematic steps which can normally be handled on an as-needed basis with the github workflow (and by extension the Linux workflow). I'm not sure these branching “rituals” are needed for this project.

**Comment by jcohenadad** [comment]
Thank you for the info @zougloub. In light of these arguments i would be in favour to roll back to the previous status quo. I would replace the wiki table with something like: 

"Please name your branch with the following convention: [Name acronym]_[function and/or action using camelCase convention]. No need to add "sct_" on function name to save space. Examples: `jca_pipeline_violin`, cg_deepseg_sc_fix`, `jc_install_language_fix`.

Please vote with thumbs up/down and/or add comment

**Comment by jcohenadad** [comment]
actually, how about benefiting from github's hierarchical system and doing the following instead: `jca/pipeline_violin`, `jca/propseg_flag_rescal`, `cg/deepseg_sc_fix`, `jc/install_language`?

That would clarify the local branches that we are assigned to (i am using sourcetree, which deals nicely with these "/")

**Comment by abtahizadeh** [comment]
I suggest, at least:
- Having `branch-[version]` instead of only one `release` to maintain releases 

- Not keeping many branches active, and deleting them while merged. (there are 20 active branches right now)

**Comment by jcohenadad** [comment]
thank you for the feedback @abtahizadeh, regarding the naming of release branches, we can easily track them using tags, so i am not sure what would be the need for creating specific release branch names.

regarding the deletion of merged branches: yes i agree, this has now been added to the CONTRIBUTION.md (in PR). Regarding the deletion of the current stale branches: i'll do it when i have some time

**Comment by abtahizadeh** [comment]
Using tags limits the ability to maintain releases (they're immutable, therefore you need to have a new tag per commit) unless you don't maintain releases.

**Comment by jcohenadad** [comment]
We currently don't maintain releases. If we do one day, we will revisit the naming of release branches.
