### ISSUE TITLE
clean msct_smooth

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#189]
This module really needs some refreshments. It is difficult to know what are the methods to use and what are the internal methods.

The return values need to be consistent... Sometimes in 2D, 3D, with or without derivatives, etc.

Needs more comments.

**Comment by joshuacwnewton** [comment]
Considering `msct_smooth` no longer exists, and we now have `sct_smooth_spinalcord` and `sct_maths --smooth`, I believe this issue is too outdated to be useful.

I think the general theme of the issue falls under the current Python API-ification efforts (i.e. general conventions for organizing high-level/low-level functionality). So, if further work is needed, I think it can be addressed in future refactoring efforts.
