### ISSUE TITLE
Build crashes on Travis/Linux running TF-based tests

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1919]
### Description

Looks like there is a systematic crash of `sct_deepseg_gm` on the recent builds. Example [here](https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/402954539#L1520). To my knowledge nothing has changed in the related code recently, so maybe there has been changes on Travis side?

**Comment by perone** [comment]
Was something changed recently to add parallelization on the `sct_testing` ? This might be the issue, because now there are multiple processes at same time and eating more memory, then `sct_deepseg_gm` is being killed.

**Comment by perone** [comment]
So, there is nothing we can do any more on the side of the application, since reducing the batch wasn't enough to solve the issue. The only options now are:

1. Refactor the `sct_testing` to avoid multiprocessing when running deep learning methods;
2. Disable parallelism on Travis build;

I'm changing the title of this issue given that it is related to Travis and `sct_testing` and not `sct_deepseg_gm`.

**Comment by jcohenadad** [comment]
i would vote for 1
