### ISSUE TITLE
Unclear number of control points for computing shape along centerline

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1942]
### Description

In `sct_process_segmentation.compute_shape()`, the shape is computed along the centerline by fitting NURBS with a given number of control points, which is 5x the number of slices in the image, as shown here: https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/msct_shape.py#L249

I am wondering why shape isn't computed per slice, as it would be 5x faster, and also users are interested in the per-slice information (not the interpolated shape between slices).

@benjamindeleener could you please comment?

**Comment by jcohenadad** [comment]
OK, my understanding is that we need to compute properties in the plane orthogonal to the cord centerline, and the decision to use 5x more points along the curve is to have a safe representation of the cord shape between two consecutive slices. Hence, the approach is to over sample, compute shape, and then average for each slice.

**Comment by Nicolas-Pinon** [comment]
The number which is 5x times the number of slices in the images on this function is not the number of control points but the number of points in the NURBS. As demonstrated on the figure attached which is issued from the test data of the SCT Paris 2018 course : 
<img width="869" alt="screen shot 2018-10-17 at 10 58 42 am" src="https://user-images.githubusercontent.com/34742864/47105667-96708180-d212-11e8-9c95-fda33ad3adac.png">
The number of points provided by the centerline image is around 230 (red) and the fitting is done using the control points (green), the result (blue) has 5 times the number of slices of the original image (320 -> 1600).
As for the reason for why there is 5 times more points even though the shape is computed per slice, I think you were right when you said : 
> we need to compute properties in the plane orthogonal to the cord  centerline and the decision to use 5x more points along the curve is to have a safe representation of the cord shape between two consecutive slices. Hence, the approach is to over sample, compute shape, and then average for each slice.

Since in the code some properties are calculated based on the plane orthogonal to the spinal cord. 

I would suggest de-linking this issue to #2038 because the later deals with the number of control points and not the sampling of the NURBS curve.

**Comment by jcohenadad** [comment]
> I would suggest de-linking this issue to #2038 because the later deals with the number of control points and not the sampling of the NURBS curve.

agreed

**Comment by Nicolas-Pinon** [comment]
Whoops, I deleted my comment by mistake, as there is no way of retrieving deleted comments to my knowledge, for the sake of clarity I will re-write  it : 

The number which is 5x times the number of slices in the images on this function is not the number of control points but the number of points in the NURBS. As demonstrated on the figure attached which is issued from the test data of the SCT Paris 2018 course :

<img width="869" alt="screen shot 2018-10-17 at 10 58 42 am" src="https://user-images.githubusercontent.com/34742864/47108334-68db0680-d219-11e8-9e20-a29fa5db298a.png">

The number of points provided by the centerline image is around 230 (red) and the fitting is done using the control points (green), the result (blue) has 5 times the number of slices of the original image (320 -> 1600).
As for the reason for why there is 5 times more points even though the shape is computed per slice, I think you were right when you said :

> we need to compute properties in the plane orthogonal to the cord centerline and the decision to use 5x more points along the curve is to have a safe representation of the cord shape between two consecutive slices. Hence, the approach is to over sample, compute shape, and then average for each slice.

Since in the code some properties are calculated based on the plane orthogonal to the spinal cord.

I would suggest de-linking this issue to #2038 because the later deals with the number of control points and not the sampling of the NURBS curve.
