### ISSUE TITLE
A way to calculate signal to noise ratio?

### ISSUE THREAD

**Issue by Aaronearlerichardson** [neuropoly/spinalcordtoolbox#1950]
For fmri there is a code to calculate temporal SNR but I could not find one for dmri. I'm hoping use this to adapt the motion correction function on a patient by patient basis in the sct_pipeline.

**Comment by jcohenadad** [comment]
hi @Aaronearlerichardson, it is not trivial to estimate SNR for DWI time series, because there are different ways this could be achieved, e.g., based on b=0 images only or based on single-direction DWI scans. Obviously, you don't want SNR to be biased by the property of the tissue wrt. its diffusion attenuation. There are ways to do each of these things in SCT, but first, could you please let us know how you would like to compute tSNR from DWI data?

**Comment by Aaronearlerichardson** [comment]
This is a little beyond my area of knowledge, but I think calculation from b=0 images makes the most sense here. All I need is a numerical indicator of image quality.

**Comment by jcohenadad** [comment]
indeed, calculating tSNR from the b=0 data is reasonable. However, before doing so, they need to be registered together, using nearest neighbour interpolation (because trilinear or spline alters noise properties, and hence upward bias tSNR estimation). An example code below:
~~~
# separate DWI and b=0 data
sct_dmri_separate_b0_and_dwi -i dmri.nii.gz -bvec bvecs.txt
# segment cord from mean DWI data (more robust)
sct_propseg -i dwi_mean.nii.gz -c dwi
# create mask (for more accurate motion correction results)
sct_create_mask -i b0_mean.nii.gz -p centerline,dwi_mean_seg.nii.gz -size 30mm -o mask_cord.nii.gz
# motion correction of b=0 data only, using nearest neighbour interpolation
sct_fmri_moco -i b0.nii.gz -m mask_cord.nii.gz -g 1 -param metric=MeanSquares -x nn
# compute tSNR
sct_fmri_compute_tsnr -i b0_moco.nii.gz 
# quantify tSNR within the spinal cord
sct_extract_metric -i b0_moco_tsnr.nii.gz -f mask_cord.nii.gz 
~~~

You will notice that we use a function called "sct_fmri_*" for DWI data, which is fine in this case because we are dealing with time series of the same contrast (like for fMRI time series).

**Comment by Aaronearlerichardson** [comment]
@jcohenadad, thank you this is very helpful.
