### ISSUE TITLE
Usage in sct_extract_metric should list the tracts based on the local info_label.txt

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1951]
Currently, when looking at `sct_extract_metric` usage, the tracts listed are taken from `$SCT_DIR/data/PAM50/atlas/info_label.txt`, however if the user edited `info_label.txt` under its working directory, `./label/atlas/info_label.txt`, which is the directory that will be used by default by `sct_extract_metric`, then the user will not see the correct list of tracts.

A solution would be to display in the usage the tracts from the `info_label.txt` file defined by the `-f` flag.

**Comment by joshuacwnewton** [comment]
This issue covers very similar territory as #2934. Leaving this open, but mentioning it so that whoever fixes #2934 can also keep these details in mind.

**Comment by joshuacwnewton** [comment]
> A solution would be to display in the usage the tracts from the `info_label.txt` file defined by the `-f` flag.

I don't think this is possible. Showing the usage happens when a user passes `-h` or provides incorrect arguments, so the value from the  `-f` argument wouldn't be available at that time.

However, if the user is providing their own `info_label.txt` file, presumably they will be aware of the contents, and will have a good idea of which values to refer to. So, I don't think it's that big of a deal if we're not able display the tracts. 

I think we could close this issue and simply focus on #2934, but what do you think, @jcohenadad?
