### ISSUE TITLE
Figuring out how to enable more thorough regression testing

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1979]
**Feature justification:** We are improving the toolbox to solve bugs, but we don't necessarily capitalize on this feedback stream as much as we could.
We could find a way to make it easy to transform candidate issues into tests, be it by adding missing unit tests, augmenting the integration tests, or having another set of regression tests.

**Describe the solution you'd like:**

- For unit tests (touching API functions), there's no reason not to augment the SCT repo.
- For other tests, it's another story. They may use data, sometimes confidential. But we are using pytest for unit tests (super-easy to use and powerful) and it could be used in the context of a testing repository (not necessarily in SCT public code as it can contain confidential data) looking like:
```
repo/
 1977-project_labels_on_spinalcord-different-orientations/
  test.py
```

The repo could use `git-annex`:
- providing deduplication of testing data (to ignore the problem of versioning it)
- with different remotes for files that can't be public, vs. those who can, so it can be distributed

The `test.py` could be doing something like:
```python
import sct_utils as sct
def test_1977():
  sct.run("sct_image -i t2.nii.gz -setorient ...")
  sct.run("sct_register_to_template ...")
  assert ...
```

I have also considered dataset durability by versioning but this is longer, and thus needs more maintenance:
```python
import os
import sct_utils as sct
from spinalcordtoolbox.datasets import sct_dataset
def test_1977():
  t2 = os.path.join(sct_dataset("sct_example_data", "1.3.1").root, "t2")
  sct.run(["sct_image", "-i", os.path.join(t2, "t2.nii.gz"), "-setorient", "..."]
  sct.run(["sct_register_to_template"], ...)
  assert ...
```

Indeed the tests could be invalidated if the interface (command-line or python) changes, so they'd need occasional maintenance.

**Comment by jcohenadad** [comment]
i like the idea of a public/private `git-annex` repo. If we go that route we should probably also talk about data structure (json that contains file name, contrast, presence+name of label, etc., where to put them, what should they contain). Currently, we have a single json (that is automatically generated from our database). 

another thing to consider is how to update this/those json (and/or the physical data, e.g. fixing a segmentation) with minimal maintenance.

**Comment by zougloub** [comment]
To be honest it was late when I posted that and I hadn't realized that this could be related to what's under the scope of `sct_testing_management`.

From the few minutes I looked at it (correct me if I'm wrong), the data under `sct_testing_management` is either "open ended", or with ground truth data for algorithm performance measurement, but not doesn't contain pass/fail criteria that *tests* would have.

As I think the task of developing an all-emcompassing solution would be more consequent, I think for now a humble repo with these test cases would fit the bill.

But on `sct_testing_management` I do think that (if possible) the metadata could be hierarchically distributed with the subjects / subject groups, *a la* BIDS, while still having a centralized cache for the HTTP service if there are performance benefits.

**Comment by jcohenadad** [comment]
@zougloub the scope of `sct_testing/large` is indeed used for algorithm performance measurement, but could also be (and currently is) used for integrity testing. E.g., the ground truth segmentations could be used to assess wether an updated version of numpy would break `sct_deepseg_sc` in certain isolated cases of image configuration (resolution, orientation, dynamic range, etc.). So I understood this issue was related to this dataset, and how to organize it properly so that it can easily be incorporated into SCT testing framework (e.g. json management, downloading it from private repos if testing on Compute Canada, etc.).

Re: json inside each folder vs. centralized on: as long as the centralized json is always updated (which is supposed to be the case also for non-centralized json), i don't see any problem in having a single centralized one. This does not follow BIDS, but in that use case, i find it fits our needs better (faster, don't have to write/modify file on the physical MRI database)..

**Comment by joshuacwnewton** [comment]
If I understand correctly, this issue was created during a time before `spine-generic` and our use of git-annex for `data-multi-subject`. Also, `sct_testing_management` has not received commits in over 2 years. So, I think the information in this issue is too outdated to be useful.

Improving our testing is certainly still a priority, but I believe that's better served by fresh discussion with the current dev team.
