### ISSUE TITLE
from msct_image import Image ImportError: No module named msct_image

### ISSUE THREAD

**Issue by chienc1** [neuropoly/spinalcordtoolbox#2024]
Dear All, 

 I am running SCT for 2D spinal cord segmentation and all goes well until the very end.

I installed the newest developer version of SCT (v3.2.4) and still the same error:

Traceback (most recent call last):
  File "metrics.py", line 10, in <module>
    from msct_image import Image
ImportError: No module named msct_image

I am running on macOS High Sierra.

Even when I remove all other python/miniconda paths in my bash profile this error occurs.

Could you please help me figure this out?

All the best, 
Claudia

**Comment by zougloub** [comment]
Hi @chienc1,

The code string `from msct_image import Image` is not present anymore in v3.2.4
(except in the /dev folder which is a sandbox).

By any chance, do you have several SCT installations and your environment's SCT_DIR is pointing at the “wrong” one?

```sh
echo $SCT_DIR
```

If so, try to `unset SCT_DIR` and run your command again.

@jcohenadad I think this `SCT_DIR` thing doesn't have a reason to be anymore since the code can figure out where it is by itself.

**Comment by charleygros** [comment]
Small detail: @chienc1 is referring to this herebelow line of a script using the SCT to reads and analyses nifti images:
https://github.com/sct-pipeline/claudia/blob/master/metrics.py#L10

**Comment by jcohenadad** [comment]
@charleygros thank you, this is helpful to know. Since v3.2.4 does not have msct_image anymore (now in `spinalcordtoolbox.image` module), could you please update this part of the script in sct-pipeline/claudia, and update the README to specify the compatible version of SCT (currently it says "working with 3.2.1 or above"). I would suggest to tag the current version of the repository (e.g. v1.0), then create a PR with the modif, then merge, then tag the new version of the repos (e.g. v2.0), so we can easily assign a tag with a working version of SCT (e.g. v2.0 --> tested with v3.2.4).

@zougloub looks like SCT_DIR is not causing the problem here, and we still use this variable to propose  generic pipelines, e.g. here: https://github.com/neuropoly/spinalcordtoolbox/blob/master/batch_processing.sh#L103

**Comment by zougloub** [comment]
OK. I'm actually hinting at removing dealing with SCT_DIR inside the code itself @jcohenadad

**Comment by charleygros** [comment]
@jcohenadad : Ok, will do and keep you updated.

**Comment by jcohenadad** [comment]
> OK. I'm actually hinting at removing dealing with SCT_DIR inside the code itself @jcohenadad

ah! yes of course, 100% agree with that

**Comment by chienc1** [comment]
Thanks so much! Looking forward to the updated script :)

**Comment by charleygros** [comment]
@jcohenadad :
- tag v1.0 created
- modfis made and then pushed/merged
--> I wait for @chienc1 feedback before to create the tag v2.0
Thanks

(issue could certainly be closed)

**Comment by chienc1** [comment]
Thanks all! Will let Charley know how it goes :)

**Comment by charleygros** [comment]
I am reporting the below issue on behalf of @chienc1:
```
Spinal Cord Toolbox (version: 3.2.4)
Sourcing sct_laucher in your environment /Applications/MR_Applications/SCT
Traceback (most recent call last):
  File "metrics.py", line 18, in <module>
    import spinalcordtoolbox.image as msct_image
  File "/Applications/MR_Applications/SCT/spinalcordtoolbox/image.py", line 24, in <module>
    from msct_types import Coordinate
ImportError: No module named msct_types
```
when running:
https://github.com/sct-pipeline/claudia/blob/master/metrics.py#L18

**Comment by zougloub** [comment]
Obviously we don't want stuff inside the `spinalcordtoolbox` namespace to call things in `scripts` but right now this is WIP.
Please add `$SCT_DIR/scripts` to PYTHONPATH (or sys.path) and it should work.

**Comment by jcohenadad** [comment]
can we close this @chienc1?

**Comment by chienc1** [comment]
@jcohenadad sorry, I am on conferences and work trips until next Monday... can I try it out and let you all know then? Thank you so much for the time and help as always :)

**Comment by charleygros** [comment]
Issue resolved.
