### ISSUE TITLE
New module to detect C2-C3 disc

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2066]
In its current implementation (v3.2.7), `sct_label_vertebrae` is poorly robust for detecting C2-C3 disc. It is an important first step for the algorithm, if it fails the rest of the processing fails.

It would be nice to develop a separate, more robust, module that detects C2-C3 disc.

**Comment by charleygros** [comment]
I recently worked on a module that detects C2-C3 disc. Please find here-below some details about it.

### Inputs:
- raw image (eg `t2.nii.gz`)
- SC segmentation mask (eg `t2_seg.nii.gz`) (note: the module also works if a centerline is input instead of the segmentation)
- contrast: `t2_like` or `t1_like`

### Main processing steps:
1. Flatten sagittal
2. Extract mid-slice (note: in my experience, using the mid-slice only (versus averaging 3 mid-slices) is preferable, thanks to the flattening. But this might need further investigations.)
3. Run detection of C2-C3 disc pattern on the extracted mid-slice using a model trained on data with similar contrast --> output an heatmap where the value of each voxel represents the likelihood to be the targetted structure.
4. Find the voxel with the maximum value of the heatmap, in a close neighborhood of the spinal cord (`sct_create_mask -size 50`).

### Output:
- a zeros_like image where one voxel has been assigned 3 as value.

### Implementation:
I am hesitating between two options:
1. integrate this module as part of `sct_label_vertebrae`
    Pros:
    - have all methods related to the disc/vertebrae detection in the same place.
    Cons:
    - currently the detection of C2C3 disc is done on the straighten cord [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_label_vertebrae.py#L500) while the proposed method use the not straighten data.
2. create a new function (e.g. `sct_detect_c2c3`). Its output could be input in `sct_label_vertebrae -initlabel label_c2c3.nii.gz`. Its implementation would be quite similar to [sct_detect_pmj](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_detect_pmj.py)
    Pros:
    - the function is quite fast (no straightening...etc., <30s for a classic t2w image) --> it could allow the user to quickly check the accuracy of this important first step of the vertebrae labelling.
     - for some applications, we do not need the labelling of the entire cord, but a single common anatomical reference across subjects (eg PMJ, C2C3-disc).
    Cons:
     - Add a command in the processing pipelines.

A compromised solution would be to create a new standalone function but to call this method in `sct_label_vertebrae` via a parameter refering to the used method (eg `corr3d` or `svm`) or by default.

**Comment by jcohenadad** [comment]
@charleygros fantastic! here are some thoughts:
- for the output label, do we agree that the label will be centered at the posterior tip of the C2-C3 disc?
- in terms of implementation: I would suggest to follow the current move towards a `spinalcordtoolbox` Python library, with modules that take as input/output matrices (instead of file names) and with associated unit test. The i/o would be done by the API (typically our `sct_xxx` scripts). So in this case, you could create a module (e.g. spinalcordtoolbox/vertebrae/detect_c2c3.py), which would be called by `sct_label_vertebrae` (before straightening).

**Comment by charleygros** [comment]
Thank you for your feedback @jcohenadad. Sounds good to me.

Centered at the posterior tip of the C2-C3 disc:
![label_c2c3_pred](https://user-images.githubusercontent.com/14353425/48820189-f0cba780-eda7-11e8-880d-34db1ff89cf1.png)

**Comment by jcohenadad** [comment]
@charleygros is there already a version that I can test for T1w data (if not, for T2w)?  The reason I'm asking is because I am currently updating the [spine-generic](https://github.com/sct-pipeline/spine_generic) pipeline for processing the spinal cord MRI public database, and having an automatic way of getting C2-C3 would be fantastic (currently done manually).

**Comment by charleygros** [comment]
@jcohenadad: A version will be ready to test mid-next week. Hope it will not be too late to be integrated.
