### ISSUE TITLE
Output segmentation has different sform/qform than input

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2106]
When using `sct_deepseg_sc` in images where qform and sform are different, the output segmentation "forces" both sform and qform to be the same. When viewing images with fsleyes/fslview, this is not a problem because these software give priority to the sform, however when using other soft such as MITKworkbench, the seg and input image are not aligned. 

N.B. there is no issue when using propseg, i.e., the s/qform are exactly the same ones as the input image.

### To reproduce
**data:** duke:sct_testing/issues/20181218_issue2106/

**syntax:**
~~~
sct_deepseg_sc -i Subject9_MPRAGE.nii.gz -c t1
~~~

### Related issues
https://github.com/neuropoly/spinalcordtoolbox/issues/1896
https://github.com/neuropoly/spinalcordtoolbox/issues/2025

Also see:
https://sourceforge.net/p/spinalcordtoolbox/help/6/
https://nipy.org/nibabel/nifti_images.html

**Comment by zougloub** [comment]
Note on the ITK behavior: https://github.com/ANTsX/ANTs/issues/500#issuecomment-333543715

ITK NIFTI1 IO decided to give priority to the qform instead of the sform (maybe because it fixates the frame origin), which is not what other software does.

**Comment by jcohenadad** [comment]
Possibly a recent change in ITK's priority over the qform? https://itk.org/pipermail/insight-users/2017-March/054351.html

In any case, we currently have a problem in SCT because we use both ITK (e.g., propseg, ANTs) and nibabel (most i/o, e.g. for deepseg_sc). So we should decide what to do if the two are not consistent, in order to ensure a coherent management of the q/sform within SCT. 

The bottomline is that SCT is supposed to be a preprocessing software, so it should take raw images as input (i.e. qform preferred, and typically q/sform should be the same). If they are not the same, then we could maybe raise an error, and ask the user to run a function that will copy the current sform into the qform (or the other way around?). 

Some software raise an error in case of q/sform mismatch (e.g., [fmriprep](https://neurostars.org/t/fmri-prep-error-mismatched-qform-sform-matrixes/1767)).

**Comment by zougloub** [comment]
According to your link ITK tools are properly following the spec (https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/qsform_brief_usage) since 2017-12, which is nice.

However:
- our ITK binaries have been compiled earlier than that
- we are also not following the spec (and somehow I missed that document when working on Image, I was thinking that sform was simply an update over qform, or something like that)

Because according to the spec, the use of qform/sform should depend on the operation, fixing the root cause isn't going to be immediate.

I'll try to reproduce this particular problem and see what we can come up with (maybe asking the user to run fslorient when sform and qform codes are "conflicting").
