### ISSUE TITLE
Centralize image creation for unit testing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2161]
The idea here is to have a single file that has functions used to create Image(), nibabel or nipy images used for testing SCT functions. Currently, many unit tests do similar things, e.g.: 
- `test_image` 
- `test_process_seg` 
- `test_centerline` 
- `test_deepseg_sc` 
- `test_deepseg_lesion` 

The common function should have different features to create synthetic images, including: 
- Have a dummy segmentation inside the volume
  - shape={'rectangle', 'ellipe'}
  - angle=15 [deg]: Angle between the segmentation centerline and SI axis
  - a=50.0, b=30.0 [mm]: width, heigh of the segmentation (if ellipse; the two radii)
- size_arr=(9, 9, 9): Size of the image
- subsampling=1: int >=1. Subsampling factor along z. 1: no subsampling. 2: centerline defined every other z.
- hasnan: Bool: Image has non-numerical values: nan, inf. In this case, do not subsample.
- orientation: RPI, etc. orientation of the image
- type of image: Image(), nipy or nibabel

**Comment by joshuacwnewton** [comment]
Closing, as it looks like we have `spinalcordtoolbox/testing/create_test_data.py` for this now, which was created in #2200 and has undergone quite a few updates since. 

It's used by most (but not all) of the functions quoted in the description here. It's possible that even more tests could be updated to use this, but, I think the core of this issue has been addressed.
