### ISSUE TITLE
Straightening glitches

### ISSUE THREAD

**Issue by lrouhier** [neuropoly/spinalcordtoolbox#2210]
### Description

Glitches in the output of sct_straighten_spinalcord. Seems to work better on the docker version than on the GitHub version. 

### Steps to Reproduce

OS: OSX mojave
0. Install SCT git version (git pull 02/04/2019)

1. `sct_deepseg_sc -i ANU-005-t2.nii -c t2`

2. sct_straighten_spinalcord -i ANU-005-t2.nii -s ANU-005-t2_seg.nii 

3. open ANU-005-t2_straight.nii 

File in Duke/sct_testing/issues/201904_issue_straighten_lurou/

**Comment by jcohenadad** [comment]
issue might be related to the poor resolution in the RL direction.

**Comment by jcohenadad** [comment]
Note from @lrouhier: the issue also appears when resampling the input data to 0.6mm iso

**Comment by jcohenadad** [comment]
i can reproduce

**Comment by jcohenadad** [comment]
The issue does not appear as much in v3.2.7. See below comparison v4.0.0-beta.2 vs. v3.2.7:
![anim](https://user-images.githubusercontent.com/2482071/55585898-bbd84580-56f5-11e9-91c3-f6a2c84eba36.gif)

**Comment by jcohenadad** [comment]
The problem was related to the bspline fitting, which captures outlier points:
![Screen Shot 2019-04-05 at 10 31 53](https://user-images.githubusercontent.com/2482071/55637269-a402cf00-5792-11e9-9983-a8775e6da07e.png)

When using polyfit (degree 10), this problem does not occur and the straightening is cleaner:
![fig_centerline_190405110200309075_polyfit](https://user-images.githubusercontent.com/2482071/55637312-bbda5300-5792-11e9-9861-4a84212f88c8.png)


![Screen Shot 2019-04-05 at 11 03 55](https://user-images.githubusercontent.com/2482071/55637289-b11fbe00-5792-11e9-9763-6ecdb347792a.png)

**Comment by jcohenadad** [comment]
This raises concerns in having **bspline** being the default algorithm for important functions: `sct_register_to_template`, `sct_straighten_spinalcord`.

Further UT should be deployed.
