### ISSUE TITLE
NURBS is broken

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2258]
Recent changes broke the integrity of nurbs output, see example below:

to reproduce:
~~~
cd sct_example_data/t1
sct_straighten_spinalcord -i t1.nii.gz -s t1_seg.nii.gz -param algo_fitting=nurbs -o t1_straight_algo-nurbs.nii.gz
~~~

nurbs:
![Screen Shot 2019-05-09 at 11 07 03](https://user-images.githubusercontent.com/2482071/57464368-971e4300-724a-11e9-86e8-997661a87d0b.png)

polyfit:
![Screen Shot 2019-05-09 at 11 07 00](https://user-images.githubusercontent.com/2482071/57464383-9f767e00-724a-11e9-8789-3c567754f6a6.png)

**Comment by benjamindeleener** [comment]
I was able to reproduce the error and fix it (PR #2292).

The error was due to the derivative of the fitted centerline that was wrongly passed to the straightening algorithm. Indeed, the centerline position and derivative can be approximated using different algorithms, including NURBS, and this information is then used in the class `Centerline` to compute the coordinate system of each point along the centerline. It is important that the derivative of the curve is calculated correctly. An error was introduced when adding new fitting approaches, by removing the Z component of the derivative and forcing it to 1. **This is a mistake.**

Below are the centerline fitting and the straightening result. Note that I corrected slightly the segmentation provided by `sct_propseg` to remove edge effects. Also, note that the segmentation was not good at the thoracic level (over-segmentation).

**Using NURBS**
```
sct_straighten_spinalcord -i t1.nii.gz -s t1_seg_manual.nii.gz -param algo_fitting=nurbs -o t1_straight_algo-nurbs-manual.nii.gz
```
![fig_centerline_190603104900841981_nurbs](https://user-images.githubusercontent.com/7757117/58811275-806ed000-85ed-11e9-9890-13237d8fca8a.png)
![Screenshot from 2019-06-03 10-51-58](https://user-images.githubusercontent.com/7757117/58811365-a98f6080-85ed-11e9-8af6-239c956536b6.png)

**Using bspline**
```
sct_straighten_spinalcord -i t1.nii.gz -s t1_seg_manual.nii.gz -param algo_fitting=nurbs -o t1_straight_algo-nurbs-manual.nii.gz
```
![fig_centerline_190603105254476023_bspline](https://user-images.githubusercontent.com/7757117/58811435-ce83d380-85ed-11e9-9ece-606320e72333.png)
![Screenshot from 2019-06-03 10-53-47](https://user-images.githubusercontent.com/7757117/58811483-e3f8fd80-85ed-11e9-9a6d-ad186cf9c383.png)
