### ISSUE TITLE
Installation failing on 4.0.0

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2399]
Likely related to Python3 (since 4.0.0_beta.2 is working and is relying on Py2k).
More info at: http://forum.spinalcordmri.org/t/sct-4-0-0-install-failed-failed-to-build-wheel-for-nipy/138

Note that the user is using .zshrc, but I don't think this is related to the issue.

@gmotzespina can you please have a look at it?

**Comment by gmotzespina** [comment]
Sure think, I'll take a look at it.

**Comment by gmotzespina** [comment]
I've tried in two different MacOS environments but I haven't been able to reproduce this issue yet. 

The devices are 
- MacBook Pro 2018
- MacBook Pro late 2013

Both on `macOS Mojave 10.14.6`

```
SCT version ......... dev
Installation type ... in-place
Operating system .... osx
Shell ............... /Users/gmartinez/.zshrc
sudo mode ........... 0
```

My steps in order to try to reproduce this issue were: 

1. Remove all **spinalcordtoolbox** related content from the machine
2. Remove the env vars from the .`zshrc` file 
3. git clone the project
3. Run `./install_sct`

Am I overlooking at something? Do you recommend me any further steps to dig into this? @jcohenadad

**Comment by jcohenadad** [comment]
@gmotzespina looks like the issue appears with [Xcode-based gcc](http://forum.spinalcordmri.org/t/sct-4-0-0-install-failed-failed-to-build-wheel-for-nipy/138/5?u=jcohenadad). Is you gcc from Xcode or did you install it using external source (e.g. from brew)?

**Comment by jcohenadad** [comment]
This PR https://github.com/neuropoly/spinalcordtoolbox/pull/2414 might solve this issue. This will need to be verified by the user once the PR is merged.

**Comment by jcohenadad** [comment]
also: i have gcc-xcode on my mac and install went well. @gmotzespina did you do more investigations on this?
