### ISSUE TITLE
sct.mv in sct_utils.py and temp space

### ISSUE THREAD

**Issue by baxpr** [neuropoly/spinalcordtoolbox#2419]
Not sure what's going on here - bug, or just some weirdness with singularity containers. But I thought I'd holler. The practical significance to me so far is that the `fmri_moco_params.tsv` file isn't getting copied from the temp dir to the output/working dir. 

    Traceback (most recent call last):
      File "/opt/sct/scripts/sct_fmri_moco.py", line 452, in <module>
        main()
      File "/opt/sct/scripts/sct_fmri_moco.py", line 225, in main
        sct.mv(os.path.join(path_tmp, 'fmri_moco_params.tsv'), os.path.join(path_out + file_data + param.suffix + '_params.tsv'))
      File "/opt/sct/scripts/sct_utils.py", line 421, in mv
        os.rename(src, dst)
    OSError: [Errno 18] Invalid cross-device link: '/tmp/sct-20190821183953.774530-fmri_moco-kvn3v5rh/fmri_moco_params.tsv' -> './fmri_moco_params.tsv'

**Comment by jcohenadad** [comment]
hi @baxpr,

your config system seems unhappy about the move. Copying the file (instead of moving) might solve the issue. And since the source is in a temp directory, it will be wiped out at some point...

Before we implement the fix though, would you mind testing it on your side to make sure it works? (you clearly seem competent enough to do it):

Could you replace [this line](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_fmri_moco.py#L225) by this line:
~~~
    shutil.copyfile(os.path.join(path_tmp, 'fmri_moco_params.tsv'), os.path.join(path_out + file_data + param.suffix + '_params.tsv'))
~~~

If you are motivated enough, you could even submit a PR from a fork to save me a few minutes ;-)

**Comment by baxpr** [comment]
Thanks! That fixed it for me. I don't really understand forks but I had a go:
https://github.com/neuropoly/spinalcordtoolbox/pull/2420
