### ISSUE TITLE
Command "which" is not installed by default

### ISSUE THREAD

**Issue by gmotzespina** [neuropoly/spinalcordtoolbox#2433]
### Description

When running `sct_install` the script checks that some dependencies are installed on the OS before proceeding with the installation. To look up for those dependencies `which` needs to be installed. 

It seems that some OS don't have `which` installed by default, so the installation fails.

### Steps to Reproduce

1. 
```
# in Terminal
docker pull centos:latest
docker run -it centos:latest
# in docker container
yum -y install git bzip2 gcc
```

2.
```
git clone https://github.com/neuropoly/spinalcordtoolbox.git sct
cd sct
yes | ./install_sct
```
Output: 
```
[root@82fe36d77cef sct]# which wget
bash: which: command not found
```

**Expected behavior:** Installation completes successfully

**Comment by jcohenadad** [comment]
@gmotzespina why is step 0 needed?

**Comment by jcohenadad** [comment]
also: i don't think this issue is specific to CentOS7 (the docker container is curated, and other CentOS7 distros do have `which` installed). Moreover, this could also happen with distros other than CentOS7.

So: we should generalize this issue, and simply check if "which" is installed at the beginning of the installer. If not, we inform the user.

Regarding the docker doc: you can simply add `which` install on the docker container

thanks 👍

**Comment by gmotzespina** [comment]
@jcohenadad I've updated the issue to be more general. I'll add on the docs the which installation step.

**Comment by gmotzespina** [comment]
@jcohenadad I did the same with `curl` since it wasn't specified on the docs and it was a step I needed to do before being able to proceed with the installation.

**Comment by joshuacwnewton** [comment]
Closing as `which` was replaced with `command -v` in https://github.com/neuropoly/spinalcordtoolbox/pull/3102.
