### ISSUE TITLE
SCT version lost when users download a zip package of master branch

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2480]
See [this post](http://forum.spinalcordmri.org/t/label-vertebrae-fails/176?u=jcohenadad), where a user likely downloaded the zip package of master branch, instead of installing with git. In this instance, the versioning information is lost, making it difficult to know the users environment.

**Comment by jcohenadad** [comment]
should we close this? any way this could be addressed easily? @joshuacwnewton @Drulex

**Comment by joshuacwnewton** [comment]
I think it would be tricky to accommodate for this. I would also guess that this is a (relatively) rare occurrence, since a user would have to ignore the README.md/documentation. So, I think the benefit would not be worth the effort, and instead I think we should simply recommend to reinstall SCT properly if this comes up again (as you did in the original post). 

I'd say close. :slightly_smiling_face:
