### ISSUE TITLE
Displaying centerline algorithm svm while incompatible with "-brain 1" option

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2537]
In the usage, it says that the flag "-brain 1 [...] is only effective with -centerline cnn".

However, when running the command with "-brain 1", the default centerline algorithm is not changed to cnn (or the verbose is incorrect):
~~~
sct_deepseg_sc -i 3dT1.nii -c t1 -brain 1 -qc qc -r 0

--
Spinal Cord Toolbox (git-release-289bb38dc4fc6ed7af17f6ccb216c76dd8eb027d)

Config deepseg_sc:
  Centerline algorithm: svm
  Brain in image: True
  Kernel dimension: 2d
  Contrast: t1
  Threshold: 0.15
~~~

**Comment by charleygros** [comment]
Not sure of which way to go:

1. Enforce `cnn` centerline detection algo when `-brain 1`:
- Pros: brain detection quite efficient --> could speed up the processing since only slices below the "brain detection" will be further processed --> quite convenient for sagittal images with large FOV in the IS direction.
- Cons: `-centerline cnn` has been reported to be slower than `-centerline optic`

2. Use `optic` centerline detection algo when `-brain 1` and `-centerline` not specified (current behaviour)
--> the centerline (prior to segmentation step) will cover the entire IS range
--> in my experience, in those cases, the segmentation / post-processing manage quite well to stop before the brain area ("quite well" would need to be defined though).

**Comment by charleygros** [comment]
We decided to modify the usage.
