### ISSUE TITLE
Refactoring of msct_register and add more testing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2547]
Following-up on the initial refactoring of `sct_register_multimodal` and `sct_register_to_template` in #2331, a deeper refactoring is needed. Notably:
- Move `msct_register` into a proper Python module: spinalcordtoolbox/register/register
- Move `msct_register_landmarks` into spinalcordtoolbox/register/landmarks
- Add unit tests for the rotation estimation. To do so, generate an image, rotate it by a known angle and run each method.

**Comment by Drulex** [comment]
Started looking at this. There is a bunch of code that has dependencies in the `scripts/` folder.

My strategy will be:
1. Move the high-level stuff in `sct_register_to_template.py` and `sct_register_multimodal.py`.
2. Move the lower-level stuff in `spinalcordtoolbox/register/register.py` and  `spinalcordtoolbox/register/landmarks.py`.
3. Refactor low-level functions that don't respect proper layering (e.g. depend on stuff in `scripts/`).
4. Further refactor low-level functions following proper API best practices.

**Comment by jcohenadad** [comment]
@Drulex excellent strategy! I just wanted to add that `spinalcordtoolbox/register/register` & `spinalcordtoolbox/register/landmarks` was only a suggestion, based on a quick analysis of the situation. If you find that other organization makes more sense, please feel free to suggest.

**Comment by Drulex** [comment]
@jcohenadad I noticed that some registration functions make `subprocess.Popen()` calls to `ANTS` binaries. I would like to avoid this type of code in the API, mainly because the API is being refactored to deal with low-level objects (Images) and this methods constraints us in creating files on the disk and passing them to ANTS.

From what I see the code calling ANTS seems to be tightly coupled to the registration logic, thus making it impossible to move the `Popen()` calls to the application layer.

I see two options:
- Use the ANTS API (https://github.com/ANTsX/ANTsPy). I haven't evaluated the effort of this, but it seems that `ANTSImage` is also based on numpy arrays so I can't imagine this would be too difficult.
- Keep using the `Popen()` calls (for now).

**Comment by jcohenadad** [comment]
> * Use the ANTS API (https://github.com/ANTsX/ANTsPy). I haven't evaluated the effort of this, but it seems that `ANTSImage` is also based on numpy arrays so I can't imagine this would be too difficult.

yes, that would be awesome indeed. Related to https://github.com/neuropoly/spinalcordtoolbox/issues/2007. Maybe during the course of this refactoring we could keep the Popen(), but at some point i would love if we could remove the system calls.
