### ISSUE TITLE
Dependencies not mentioned in the readme installation instructions

### ISSUE THREAD

**Issue by olix86** [neuropoly/spinalcordtoolbox#2575]
Currently on macOS, `gcc` installation is handled automatically via homebrew and the installer indicates which commands to run when a problem is encountered. On linux,  when gcc is missing (such as in a default ubuntu installation), the current message is `Please install "gcc" and restart SCT installation.` which is not super helpful for beginners especially since it doesn't look like the readme indicates what/how to install before running ./install_sct

[link](https://github.com/neuropoly/spinalcordtoolbox/blob/e1bb1c97c594c991ee5514003c50f47061d42fc0/install_sct#L188)

I think we should either mention the dependancies in the readme, or say something along the line of run `apt/dnf install gcc` on ubuntu/fedora

**Comment by jcohenadad** [comment]
Yes, I agree we should mention the gcc dependency in the README. 
Also, displaying more info for installing gcc on Linux would be useful, but since the method is distros-dependent maybe we can just redirect to the official gcc install page?

**Comment by olix86** [comment]
Sounds good :+1:

**Comment by jcohenadad** [comment]
> maybe we can just redirect to the official gcc install page

The problem is that [this page](https://gcc.gnu.org/install/) describes how to compile gcc, which is over-complicated for most users, given that gcc can easily be installed via package manager (apt, yum, etc.), so i suggest to instruct the latter as already done in the [README](https://github.com/neuropoly/spinalcordtoolbox/pull/2577/files#diff-04c6e90faac2675aa89e2176d2eec7d8R64)
