### ISSUE TITLE
fsleyes integration saves outputs to directory from which fsleyes is opened

### ISSUE THREAD

**Issue by valosekj** [neuropoly/spinalcordtoolbox#2579]
### Description

When run `sct_deepseg_sc` or `sct_deepseg_gm` from FSLeyes integration, segmentations are saved into directory where I have FSLeyes opened from, not to directory where the image is from. 

### Steps to Reproduce

0.  `sct_check_dependencies` output: 

> SCT info:
> version: git-master-9d0cdbc7df413ee68da3ec254b8566d379511e3c
> path: /usr/local/sct
> OS: osx (Darwin-18.7.0-x86_64-i386-64bit)`

1. Go to any directory in the terminal (e.g. /Users/user/Documents) and type `fsleyes`

2. Open some image (e.g. /Users/user/Documents/ExampleData/t1w.nii.gz)

3. Run `sct_deepseg_sc` from FSLeyes integration

**Expected behavior:** <What you expect to happen>
It makes more sense to me, if final segmentation would be saved in same directory as input image (i.e. /Users/user/Documents/ExampleData/).
**Actual behavior:** <What actually happens>
Final segmentation is saved to directory where the FSLeyes is opened from (i.e.  /Users/user/Documents/).

**Comment by jcohenadad** [comment]
As suggested, a solution would be to modify SCT's behaviour and have the default folder being the folder of the input image. However, that could potentially break many of the current workflows. 

A better solution would be to set the output folder to be the folder of the input image *only* when using FSLeyes plugin. This would require a modification on some of the SCT's function, to enable specifying the output folder (or output path file name)

**Comment by Drulex** [comment]
> As suggested, a solution would be to modify SCT's behaviour and have the default folder being the folder of the input image. However, that could potentially break many of the current workflows.

I don't thinks this is preferred because:
- It is non-standard and may be non-obvious to some users
- May generate unwanted artifacts alongside the input data, possibly even risking overwriting it we or the user are not careful

When using a CLI app it is a sane default behavior to use the current working directory when saving files, unless explicitly overridden.

When using a GUI this doesn't really apply, because it is not obvious for the user to tell what the `cwd` is. In that case the GUI should offer the user some mechanism to let him know/specify what the output directory is.

I see 2 options:
1. Let the user specify the output directory/output file. This means adding the visual elements to the GUI to let him do so.
2. Display to the user what the output directory is (the GUI knows what `cwd` is). It could show it as a text label underneath or maybe in a popup when the processing is finished.

Option `1` is definitely a better user experience. In terms of effort it is greater, but not by much.

Thoughts @jcohenadad ?

**Comment by jcohenadad** [comment]
@Drulex yes, after giving it additional thoughts, i agree 100% that my suggestion of outputting by default in the intput image folder is not a desired behaviour. 

I really like your first suggestion: "Let the user specify the output directory/output file. This means adding the visual elements to the GUI to let him do so.". I think we should go for it. Ideally, the output folder would be kept "in memory" for subsequent commands (so that users don't have to specify output folder every time).

**Comment by Drulex** [comment]
Ok so proposing the following:
- Add input text field just above the `run` button with label `Output Folder`
- When populating the output folder in a tab it will update it for the other tabs automatically
- (similar for `sct_label_vertbebrae` but requires an output file instead of folder)

![image](https://user-images.githubusercontent.com/7751484/95350404-1ecc0f00-088e-11eb-8ac5-9d501276a071.png)
