### ISSUE TITLE
SCT logo does not appear correctly when using Docker FSLeyes 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2586]
When using `sct_pluging.py` in FSLeyes via Docker, the logo is not displayed properly:
![Screen Shot 2020-01-18 at 4 51 47 PM](https://user-images.githubusercontent.com/2482071/72671105-6b776d80-3a13-11ea-8516-3daedf09914e.png)

Version: sct-docker-4.2.1

**Comment by valosekj** [comment]
Same behavior under Debian 10 Buster with MATE Environment 1.20.4.

(white background behind name of sct_deepseg_sc function is caused by bad compatibility of FSLeyes with dark MATE mode)

![SCT_logo](https://user-images.githubusercontent.com/39456460/72684280-7a2b5680-3adf-11ea-9415-55879aebacef.png)

**Comment by jcohenadad** [comment]
thanks for the feedback @valosekj. Are you interested in digging into this issue?

**Comment by valosekj** [comment]
Update: My previous post was when I used remote access by TightVNC. Now, when I open FSLeyes locally at the same machine and try to _Run script_ option I get error that SCT is not found.

So, apparently, the FSLeyes behavior is different when it is run locally or remotely.
I can see in _About FSLeyes_ option different OpenGL renderers:
- run locally - OpenGL renderer: Radeon 550 Series (POLARIS12, DRM 3.32.0, 5.2.0-0.bpo.3-amd64, LLVM 7.0.1)
- run by TightVNC - OpenGL renderer: llvmpipe (LLVM 7.0, 128 bits)

In both cases I use FLSeyes 0.15.2

@jcohenadad Yes, in the meantime, I will try it.

![FSLeyes_sct_run_script](https://user-images.githubusercontent.com/39456460/72721446-6124b300-3b7c-11ea-9107-849c7828cc36.png)

**Comment by jcohenadad** [comment]
> when I open FSLeyes locally at the same machine

this is just an environment variable issue. Do you open FSLeyes it from the Terminal? 

* If yes, what is the output of `sct_check_dependencies` just before you run FSLeyes?
* If no, you should open FSLeyes from the Terminal (as instructed)

**Comment by valosekj** [comment]
Yes, I run FSLeyes from the terminal. Problem was in missing line in my `bashrc` file. From some reason, I had there only line for adding SCT into `$PATH` but  `$SCT_DIR` variable definition was missing.
Thanks!

**Comment by valosekj** [comment]
Setting size of SCT logo by `Scale` method instead of `SetSize` before converting it to bitmap helped me on Debian 10:

https://github.com/neuropoly/spinalcordtoolbox/commit/8ee7318c9264bc8ee8eeda04469f1f2262f4252e

![FSLeyes_SCT_logo_Debian10](https://user-images.githubusercontent.com/39456460/78389664-62924300-75e3-11ea-9f34-3d84e442eada.png)
