### ISSUE TITLE
Broken link to PAM50 on OSF

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2649]
https://github.com/neuropoly/spinalcordtoolbox/blob/266bfc88d6eb6e96a2c2f1ec88c2e185c6f88e09/scripts/sct_download_data.py#L93

the link should be: `https://osf.io/u79sr/download`

**Comment by htp2** [comment]
I added a pull request for this (#2671). 
This caused me some issues installing the toolbox (I am a new user), since the install script would hang at this line, never getting to configurations, editing the .bashrc, etc., so none of the commands worked. Thank you for raising the issue as the change got it working.

**Comment by kousu** [comment]
Thanks for this @htp2! It should fall back to the second mirror, but I noticed that our second mirror was also hanging. I wonder if what happened is actually that this link never worked and it was always using the second mirror, but that has become overloaded in the last couple weeks.
