### ISSUE TITLE
Torch-cpu installation in Spinal cord Toolbox

### ISSUE THREAD

**Issue by lrouhier** [neuropoly/spinalcordtoolbox#2712]
Following issue [208](https://github.com/neuropoly/ivado-medical-imaging/issues/208) from Ivadomed. 
The pytorch-cpu installation is OS-specific due to a lack of availability of CUDA package for OSx.

One solution could be to add : 
~~~
case $OS in
linux*)
        pip install torchvision==0.6.0+cpu torch==1.5.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html;;
osx)
        pip install torch==1.5.0 torchvision==0.6.0;;
esac
~~~
[here](https://github.com/neuropoly/spinalcordtoolbox/blob/f80551b61639f46e93760dc8329dba74aad24559/install_sct#L533)

But I am not sure if this is the best solution.

**Comment by lrouhier** [comment]
@kousu do you have an opinion?

**Comment by kousu** [comment]
:sob: I'll look at this tomorrow.

**Comment by kousu** [comment]
I think this should do it:

https://www.python.org/dev/peps/pep-0508/#environment-markers:

```
torch==1.5.0+cpu ; sys.platform != "darwin"
torch==1.5.0 ; sys_platform == "darwin"
```

**Comment by kousu** [comment]
Tangentially, `requirements.txt` has support for optional dependencies. They call them [extras](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) and we're using them in our own requirements.txt:

```
urllib3[secure]
```

What this means is that installing urllib3 will also install the dependencies it needs to use HTTPS. I assume (but would have to check) that urllib3 checks -at runtime- what dependencies it has available (by catching `ImportError`s), which I think is a good thing, it makes it more flexible and less fragile.

We could define a `spinalcordtoolbox[training]` extra that pulls in the full Torch install.

And in the future, if we had our models packaged in `.whl`s, we could even have people install them via extras too, say `pip install spinalcordtoolbox[lesion,c3c3,deepseg_mice_uqueensland_sc]`.

**Comment by kousu** [comment]
@jcohenadad Adding Torch is a pretty heavy change so I want to do a separate PR for this and merge it, then have you merge it into #2639.

It would:

- add the lines above to `requirements.txt`
- fix `sct_check_dependencies` to at least deal with the new format

**Comment by kousu** [comment]
@jcohenadad I've done it. I am being lazy and testing OS X in CI. I'm pretty sure it is going to work though. It needs some review -- in particular I fiddled with the `sct_check_dependencies` scanning logic because I though I found a bug, but maybe I just misread it entirely and there's a good reason it was doing what it was doing.

**Comment by ssinad** [comment]
> We could (eventually, not now) define a `spinalcordtoolbox[training]` extra that pulls in the full Torch install. **EDIT**: this is possible, but we'd have to switch from `pip install -r requirements.txt` to `pip install .` and `setup.py` because [you cannot declare extras in requirements.txt](https://github.com/pypa/setuptools/issues/1080#issuecomment-344181278); I think it's worth going in that direction though.

One downside to this is that [GitHub](https://docs.github.com/en/enterprise-server@2.22/github/visualizing-repository-data-with-graphs/understanding-connections-between-repositories/about-the-dependency-graph#supported-package-ecosystems) may not parse `setup.py` to extract dependencies.
> Note: If you list your Python dependencies within a setup.py file, we may not be able to parse and list every dependency in your project.

**Comment by kousu** [comment]
Python is in the middle of a transition away from setup.py and towards setup.cfg and pyproject.toml, because setup.py encourages people to write free form code [like this](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c951389c917884e7e3bb3c3f39aea47669a07a79/setup.py#L10-L15) whereas those formats are more restrained (people call them "declarative" right?). But they haven't settled on this yet; pyproject.toml and setup.cfg don't cover all the things setup.py can do and don't have full support everywhere.

I envision that, once pyproject.toml is actually a fully working replacement for setup.py, migrating to it in one go. But it's not ready yet, so otherwise I vote we stick to the tried-and-true canonical python methods.
