### ISSUE TITLE
Update doc for windows users with WSL2

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2747]
Looks like WSL2 has better performances (see [here](https://towardsdatascience.com/dual-boot-is-dead-windows-and-linux-are-now-one-27555902a128)), so we should update our installation doc for our windows users.

**Comment by lrouhier** [comment]
I looked at it. We just need to change the link in the respective [wiki page](https://github.com/neuropoly/spinalcordtoolbox/wiki/SCT-on-Windows-10:-Installation-instruction-for-SCT-on-Windows-subsytem-for-linux) (then the distribution is the same and everything works fine, though I need to check again). However after testing WSL2, I think we should wait for two reasons:
1- there is a restriction to the windows version (maybe show the two links)
2- WSL2 just consume a whole lot of memory. This is a known issue: https://github.com/microsoft/WSL/issues/4166 (last comment 6 days ago). There is workaround but, without it, it actually slows my laptop down because it doesn't release the memory.
