### ISSUE TITLE
Do not quit if error is encountered

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2767]
Currently, if an error is encountered, `sct_run_batch` will stop. This could be confusing for the user, who would usually expect all the database to be processed, and at the end, review all the failing cases.

related to https://github.com/sct-pipeline/spine-generic/issues/88

**Comment by kousu** [comment]
Python doesn't have a [multiexception](https://www.codeproject.com/Articles/1370/MultiException-Type-Safe-Collections-without-Colle) that I know of, but since this is a command line app you could just trust in stderr:

```
for file in files:
    try:
       upload(file)
    except KeyboardInterrupt:
        raise
    except:
        logging.exception(f'{file} failed to upload.') # this uses the global sys.exc_info()
```

**Comment by cfhammill** [comment]
A multiexception would be handy, I did something pretty similar to your suggestion, trapping errors and discarding them if the user chooses to (the default), and reraises if the user doesn't. The exception in question doesn't need to be printed to the logs because it's generated by `sct_run_batch` on a failing return code, the task script is responsible for logging itself (although I would be open to echoing it anyway).
