### ISSUE TITLE
sct_testing and pytest pointing to inconsistent sct_testing_data

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2776]
Currently in SCT, some test functions point to `os.path.join(sct.__sct_dir__/sct_testing_data)` while others will point to the local `sct_testing_data`.

We should make it consistent, and only point to the local `sct_testing_data`.

**Comment by cfhammill** [comment]
A grep of the unit tests shows all but one case use `os.path.join(sct.__sct_dir__, 'sct_testing_data...')`, I tried converting `test_deepseg.py` to use the global convention but the tests started failing. I'm trying to figure out why.

I can see a case for using a local directory, or better yet an environment variable so that developers can work easily with modified testing data as the tests change/grow over time.
