### ISSUE TITLE
Command-line not rendered on RTD

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2834]
EDIT 2020-08-07 15:04:06: The comment below is no more accurate. The problem is that the CLI doc is not rendered on RTD, as described in https://github.com/neuropoly/spinalcordtoolbox/issues/2834#issuecomment-670270201.

This is related to SCT not being 100% installable via pip. More details in https://github.com/neuropoly/spinalcordtoolbox/issues/1526.

~I must have done something wrong in the latest commits in, but the API doc does not render anymore in the master build ed976ac5aa153137177c69a9f82031dff969fc03:~

**Comment by jcohenadad** [comment]
@Drulex do you remember if the API doc was ever rendered on RTD?

**Comment by jcohenadad** [comment]
RTD installs with the following command:
~~~
python -m pip install --upgrade --upgrade-strategy eager --no-cache-dir .[docs]
~~~
which, when calling SCT scripts, produce the following error:
~~~
(rtd-test3) julien-macbook:~/temp/rtd3 $ sct_version 
Traceback (most recent call last):
  File "/Users/julien/miniconda3/envs/rtd-test3/bin/sct_version", line 5, in <module>
    from spinalcordtoolbox.compat.launcher import main
ModuleNotFoundError: No module named 'spinalcordtoolbox.compat'
~~~

However, when installing with:
~~~
pip install -e .
~~~
the correct output is produced:
~~~
(rtd-test3) julien-macbook:~/temp/rtd3 $ sct_version 
git-HEAD-3fde06f47a1d0343a54191a5a6331811d72a55d0
~~~

**Comment by jcohenadad** [comment]
Another thing that puzzles me, is that the latest version of RTD (from master) does seem to be able to load the entry-point scripts, but then produces another error related to the absence of version.txt (addressed in https://github.com/neuropoly/spinalcordtoolbox/issues/2832):

![image](https://user-images.githubusercontent.com/2482071/89598556-196d2c80-d82b-11ea-9875-2f138762f167.png)

**Comment by Drulex** [comment]
> @Drulex do you remember if the API doc was ever rendered on RTD?

No it never rendered using RTD build's environment. It renders correctly if built locally and then hosted somewhere (e.g github pages).

I will investigate, but I rather avoid trickeries in the RTD build and instead have a proper `pip install` package.

**Comment by Drulex** [comment]
Python API doc rendering failure was caused by the project path not correctly added to the system path (fix here https://github.com/neuropoly/spinalcordtoolbox/commit/a3d78485b9121a7ecbecd7865c86954f79c21233).

Python CLI doc rendering failure is caused by the fact the RTD build only supports package install via `pip install .` or `setup.py install`, and both of them are not working as expected for the `spinalcordtoolbox` project. RTD removed support for `-e` (https://github.com/readthedocs/readthedocs.org/issues/4944)

**Comment by jcohenadad** [comment]
> RTD removed support for -e (readthedocs/readthedocs.org#4944)

😞

**Comment by joshuacwnewton** [comment]
I think I've found the start of a fix, from this [very similar StackOverflow question](https://stackoverflow.com/questions/21028165/setuptools-console-script-entry-point-not-found-with-install-but-its-found-with). Updating `setup.py` like this:
```python
    packages=[
        "spinalcordtoolbox",
        "spinalcordtoolbox.compat" # <--- New. (find_packages() may also work, but have not tested yet)
    ],
```
Gets me past the error mentioned above, but leads us to a new error.
```bash
Traceback (most recent call last):
  File "/home/neuropoly-dev/Git/spinalcordtoolbox/python/envs/spinalcordtoolbox_compat/bin/sct_version", line 8, in <module>
    sys.exit(main())
  File "/home/neuropoly-dev/Git/spinalcordtoolbox/python/envs/spinalcordtoolbox_compat/lib/python3.6/site-packages/spinalcordtoolbox/compat/launcher.py", line 25, in main
    assert os.path.exists(script)
AssertionError
```

`launcher.py` is looking for the sct scripts in `<sct_venv>/lib/python3.6/site-packages/scripts/` when the scripts were actually installed to `<sct_venv>/sct_scripts` because of this hack:

https://github.com/neuropoly/spinalcordtoolbox/blob/fce82d8c98fab1cc878c4e8c48fa1c515f0db35c/setup.py#L43-L48

It looks like this hack initially came about in https://github.com/neuropoly/spinalcordtoolbox/commit/9f6d2d2c817fde3a692a94d8403dd9c2ecf0ba2e#diff-2eeaed663bd0d25b7e608891384b7298L46. So, I think if we're looking at fixing `pip install .` long-term, reviewing why this change was made in the first place might be a good place to start.

Happy to look further into this, but I'm also not sure what your plans are @Drulex. Were you planning on working on this further?
