### ISSUE TITLE
Convert argparse '0'/'1' options to be typed as ints rather than strings

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#2843]
> **Note:** This issue was previously about converting 0/1 options to `store_true`/`store_false`. The description has now been updated to instead standardize how we do 0/1 options.

### Proposal

Our argument parsing uses integer 0/1 for "on/off" options. (This often makes more sense from a user prespective than argparse's `action="store_true"`.) However, the usage for this is often inconsistent:

* Argument is parsed as `0/1 (int)`, then checked using `if argument:`
* Argument is parsed as `"0"/"1" (str)`, then cast to `int` and checked using `if argument:`
* Argument is parsed as `"0"/"1" (str)`, then checked using `if argument == "1":`

We should update all instances of this behavior to the first method, and also update the dev Wiki with relevant info.

EDIT: This PR excludes `verbose` as our usage is slightly more nuanced (despite having similar `"0"/"1"/"2"` values).

### Related issues/PRs

* https://github.com/neuropoly/spinalcordtoolbox/pull/2819#discussion_r467516660
* #2672
* #2676 (Another project-wide argparse update for a more canonical parsing solution.)

**Comment by jcohenadad** [comment]
Related to this (for the flag verbose), is this proposed convention for putting the argparse outside the main() function, and right before calling the logging init: https://github.com/neuropoly/spinalcordtoolbox/wiki/logging#code-in-librarys-apis-eg-spinalcordtoolboxresampling

**Comment by joshuacwnewton** [comment]
When converting the `-r` option (remove temporary files), I ran into the UX issue described in https://github.com/neuropoly/spinalcordtoolbox/pull/2819#issuecomment-673125735. 

Our default behavior is to always remove temporary files. So, when `-r` is specified, it's usually `-r 0` (so that temporary files are _not_ removed instead). To translate this into `action="store_false"`, `-r` would become:

```python
    optional.add_argument(
        '-r',
        action="store_false",
        help="Don't remove temporary files."
    )
``` 

Which is less intuitive! In order to have the option fit the `-do-this` convention, it would have to be:

```python
    optional.add_argument(
        '-k',
        action="store_true",
        help="Keep temporary files."
    )
``` 

Which feels like a pretty involved change for admittedly little benefit. At this point, I think I like preserving `-r 0/[1]` and only making this change in other places.

**Comment by jcohenadad** [comment]
@joshuacwnewton given that 
- the proposed modifications (use of store_true/false) will break CLI cross-compatibility with previous versions, and that it will likely happen _after_ 5.0.0 release (which we want to make sooner rather than later)
- the current CLI is not _so_ problematic from the user standpoint (e.g., software such as ANTs use the same 0/1 flags, and our users base is used to ANTs), and has some advantages as pointed out in https://github.com/neuropoly/spinalcordtoolbox/issues/2843#issuecomment-676480553 and https://github.com/neuropoly/spinalcordtoolbox/issues/2843#issue-679437595 

I would suggest to maybe reconsider the proposed change in CLI, and mostly focus on the harmonization of the 0/1 values, ie: make sure they are all treated as `int` in SCT's code, no more as `str`, which has caused [issues](https://github.com/neuropoly/spinalcordtoolbox/pull/2842#pullrequestreview-490053403). What do you think @joshuacwnewton ?
