### ISSUE TITLE
change "rm -rf" by os.remove for deleting temp folders

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#286]
Check if this a network issue

**Comment by slevyrosetti** [comment]
It is indeed a network issue because it occurs on slevy_local's and sadup's session:

    `WITH "os.remove(path_tmp)" or "os.removedirs(path_tmp)":
Remove temporary files...
Traceback (most recent call last):
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_process_segmentation", line 746, in <module>
    main()
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_process_segmentation", line 158, in main
    compute_csa(fname_segmentation, name_method, volume_output, verbose, remove_temp_files, spline_smoothing, step, smoothing_param, figure_fit, name_output, slices, vert_lev, path_to_template)
  File "/Users/slevy_local/spinalcordtoolbox/bin/sct_process_segmentation", line 568, in compute_csa
    os.remove(path_tmp)
OSError: [Errno 1] Operation not permitted: 'tmp.150326151013/'

   `WITH "sct.run('rm -rf '+path_tmp)":
Remove temporary files...
rm -rf tmp.150326150816/

ERROR! 
rm: tmp.150326150816/: Directory not empty
Exit program.


(run command: sct_process_segmentation -i t2_seg.nii.gz -p compute_csa -z 20
with data: sct_example_data)

**Comment by jcohenadad** [comment]
ok, let's use ``os.removedirs``anyway, it's "cleaner".

**Comment by benjamindeleener** [comment]
``os.removedirs`` does not work for non-empty directories.
