### ISSUE TITLE
Wiki updates

### ISSUE THREAD

**Issue by Drulex** [neuropoly/spinalcordtoolbox#2880]
Apparently I can't make PRs for the wiki. Also showing the patch here will lead to bad formatting, because the files are in `.md` and the syntax will clash.

@jcohenadad and/or @joshuacwnewton could you take a look?

```
spinalcordtoolbox.wiki git:(master) $ git fetch
spinalcordtoolbox.wiki git:(master) $ git diff master aj/wiki-updates
```

We can discuss any concern here

**Comment by joshuacwnewton** [comment]
@Drulex Thank you for raising an issue for your WIki changes. I also had similar concerns about how we should make Wiki changes! (I have been making changes here and there, but it is awkward to alert others.) I would prefer a PR mechanism as you mention, and it is a shame GitHub doesn't offer that. 

I'll take a look in a moment (just wanted to comment on the process first).

**Comment by joshuacwnewton** [comment]
I am kind of doing a "DIY Pull Request" here since GitHub doesn't provide PRs for the Wiki! :stuck_out_tongue_closed_eyes: 

### In `Programming:-Exceptions.md`: 

+1 on the additional material! Just to check, though, what is the purpose of this `pass` here?

```python
try:
   something_right
except Exception as e:
   logger.warning("Some exception occurred: {} but we are ignoring it".format(e))
   pass
```

### In `Programming:-Moving-away-from-sct.run.md`:

```
Avoid this and instead import the functionality the proper way:

- If a script script provides a useful core functionality, this means it should be moved to the API so that it can be used by other consumers.

- I a script provieds a useful high-level functionality not relevant to the API, import that functionality instead of calling `script.main()`
```

This clarification is quite helpful! I don't think there was a section in the Wiki about the "Python APIification" efforts, so perhaps we could call this section `Transition from sct.run to Python API`? The [GitHub Project](https://github.com/neuropoly/spinalcordtoolbox/projects/7) could be linked in some way, too.

(Also, there are a few typos ("script script" and "I a script"))

### In `Programming:-API-code-vs-application-code`

Aha! Just got to this commit. I see now you had the same idea to make a dedicated page for the API efforts!

Hmm... could this page be combined with the `sct.run` page? They both cover very similar topics...

**Comment by Drulex** [comment]
> what is the purpose of this `pass` here?

To be explicit about silenced exceptions. While refactoring I saw a lot of code ignoring exceptions without explicit traces or `pass` keyword to show that the developer intended to ignore the exception. Otherwise stuff goes wrong, but the exception is never propagated so it's a pain to debug.

> (Also, there are a few typos ("script script" and "I a script"))

Good catch, will fix.

> Hmm... could this page be combined with the sct.run page? They both cover very similar topics...

Good, if the info is there twice there are more chances that people will see it ;)

**Comment by joshuacwnewton** [comment]
I thought about this a little more, and I think with developer Wiki stuff, it might be better to not open up issues/PRs like this, and instead just go ahead and make edits directly. (Similar to what was mentioned in https://github.com/neuropoly/spinalcordtoolbox/pull/2877#discussion_r486785127.)

The reason my opinion changed was because of an article titled [Internal Developer Documentation](https://www.danclarke.com/internal-developer-documentation). Some relevant excerpts:

> I should point out at this stage, that I'm not talking about product documentation to be released to customers or stakeholders. I'm talking about internal technical developer documentation in which devs can be free to add to and update existing documentation. It should be easy and effortless to do so, without friction that would come from updating publicly released product documentation.

> This is why it's important that there's little resistance to contributing, and everyone feels invested in the wiki. If someone sees that something is wrong or out of date - then it should be effortless to update it. And everyone needs to know that they should be updating things that are incorrect as soon as they spot it.

So, in this person's opinion, the dev wiki should be treated differently than our user-facing documentation (much more frequently updated, without the same lengthy approval process), and I think I agree.

**Comment by jcohenadad** [comment]
> So, in this person's opinion, the dev wiki should be treated differently than our user-facing documentation (much more frequently updated, without the same lengthy approval process), and I think I agree. Maybe, at the most, some informal chats in our Slack?

+1 for me. Multiple times in the past i noticed typos/issues here and there and I did not bother correcting them because it would take me 1min to open branch/PR + time for review vs. 10s to edit it myself. I'm sure I'm not the only one. To me, this cons largely is larger than the cons of not having systematic reviews for internal doc.

**Comment by Drulex** [comment]
I agree with your points. My only concern is that it would be nice to have some kind of consensus before publishing opinionated stuff to the wiki. I am ok with the informal slack thread post.

With that said, can I merge my proposed changes in the wiki ;)?

**Comment by jcohenadad** [comment]
> With that said, can I merge my proposed changes in the wiki ;)?

👍

**Comment by joshuacwnewton** [comment]
>  My only concern is that it would be nice to have some kind of consensus before publishing opinionated stuff to the wiki. I am ok with the informal slack thread post.

This is a very valid concern! Especially if the Wiki change involves larger design decisions. 

In addition to Slack, we also have GH issues and/or Tuesday dev meetings, I think. See #2893 for an example of preliminary discussion before a Wiki change.

> With that said, can I merge my proposed changes in the wiki ;)?

:+1:

**Comment by joshuacwnewton** [comment]
Looks like this has been merged. Thanks so much, @Drulex!

The sidebar will need to be updated as well, but that can be handled by #2861.
