### ISSUE TITLE
Broken compatibility due to previous bug in a script

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2881]
Previously, `sct_dmri_separate_b0_and_dwi` had a bug:

The default value was supposedly average=0:
https://github.com/neuropoly/spinalcordtoolbox/blob/2d29de6918f7b85bda96e8c2b6d58f720442ac77/scripts/sct_dmri_separate_b0_and_dwi.py#L34

However the input flag was converting to a string:
https://github.com/neuropoly/spinalcordtoolbox/blob/2d29de6918f7b85bda96e8c2b6d58f720442ac77/scripts/sct_dmri_separate_b0_and_dwi.py#L63

And the variable was then evaluated as a Bool, so the result was always "True":
https://github.com/neuropoly/spinalcordtoolbox/blob/2d29de6918f7b85bda96e8c2b6d58f720442ac77/scripts/sct_dmri_separate_b0_and_dwi.py#L212

The recent PR #2819 fixed that bug, but also changed the behaviour: the average scan is not more produced, which breaks all the current processing pipelines already in place, e.g. 
https://github.com/spine-generic/spine-generic/blob/4143cbfd7a206f06e3fd9f42485d5087129899d7/process_data.sh#L261

I suggest we change the default to be average=1 to ensure cross-compatibility

**Comment by joshuacwnewton** [comment]
Good catch! 

Doing a project-wide search for `=['0'` yields other examples of 0/1 flags that were parsed as strings. So, there could be other instances of this type of bug, where `if <variable>:` was always evaluating to True.

Since more of these '0'/'1' flags will be updated as a result of #2842 and #2843, I'm concerned about compatibility breaks elsewhere, too. (Especially because this doesn't seem like something our current test suite is able to catch.) Since there are only a limited number of '0'/'1' flags, I can do a quick manual inspection for other occurrences.

**Comment by joshuacwnewton** [comment]
On a first pass, I couldn't find any other instances of this bug. All other '0'/'1' options are cast to int before use, e.g.

**Comment by joshuacwnewton** [comment]
On a first pass, I couldn't find any other instances of this bug. As far as I can tell, all other string '0'/'1' options are either cast to int before use:

https://github.com/neuropoly/spinalcordtoolbox/blob/b6a3fd5c6cbb6f03b68d086721e376846d339813/scripts/sct_label_vertebrae.py#L227-L228

Or the string value is checked explicitly, e.g.:

https://github.com/neuropoly/spinalcordtoolbox/blob/b6a3fd5c6cbb6f03b68d086721e376846d339813/scripts/sct_propseg.py#L590-L592

So, I think it was just this one.
