### ISSUE TITLE
sct_run_batch is outperformed by naive for loop

### ISSUE THREAD

**Issue by leandervaneekelen** [neuropoly/spinalcordtoolbox#3036]
### Description

I have set up a pipeline for T1 -> T2 registration of images in the `spine-generic/data-multi-subject` dataset so that I can rapidly compare different registration techniques using `sct_register_multimodal`. I do my batch-calls of my `registration_pipeline.sh` script using `sct_run_batch`. 

I have noticed a very significant slowdown when using `sct_run_batch` as compared to calling `registration_pipeline.sh` with a simple for-loop across all my subjects. While a registration typically takes ~150 seconds in a stand-alone call or within a for-loop, running even 1 job using `sct_run_batch` may take over an hour. In a direct comparison experiment, a for-loop took 21 minutes and 49 seconds to process 5 subjects,  `sct_run_batch` with 5 parallel jobs took 1 hour, 37 min and 41 seconds. 

### Steps to Reproduce
I used commit 5a23e7d as my last pull when I encountered these performance issues. I have not tried running this on the latest master commit.
~~~
# BATCH CALL
start=`date +%s`
sct_run_batch \
-jobs 5 \
-path-data "/home/GRAMES.POLYMTL.CA/p114001/data_nvme_p114001/data-multi-subject-hemis_small" \
-path-output "./" \
-script register_pipeline.sh \
-script-args "step=1,type=im,algo=affine,metric=CC,iter=10,smooth=0,gradStep=0.1,slicewise=0"
end=`date +%s`
runtime=$((end-start))
echo "*** Duration *** - $(($runtime / 3600))hrs $((($runtime / 60) % 60))min $(($runtime % 60))sec"
~~~

~~~
# FOR LOOP
start=`date +%s`
while read SUBJECT; do
    bash register_pipeline.sh "${SUBJECT}" "step=1,type=im,algo=affine,metric=CC,iter=10,smooth=0,gradStep=0.1,slicewise=0"
done < subjects.txt
end=`date +%s`
runtime=$((end-start))
echo "*** DURATION OF SCRIPT *** - $(($runtime / 3600))hrs $((($runtime / 60) % 60))min $(($runtime % 60))sec"
~~~
`register_pipeline.sh` is available [here](https://github.com/ivadomed/pipeline-hemis/blob/main/register_pipeline.sh). Alternatively, the batch/for-loop scripts above also exist on `duke` in `/projects/ivadomed/leander/experiments/pipeline_speed_exp` for easy reproduction.

**Comment by cfhammill** [comment]
Hi @leandervaneekelen thanks for reporting this!

In general we expect the parallel version of the code to perform worse on a per subject basis, but not on an overall basis and definitely not by a factor of 30-60x. 

What I think is happening, is that your for loop is taking advantage of parallel computing power better than `sct_run_batch`. In the `sct_run_batch` code an environment variable `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS` is set by the the argument `-itk-threads`. This configures the number of threads (and thus cores) that ITK and ANTs code can use. If left unset this get set to 1 and compute intensive ANTs programs may be running single threaded, leading to substantial slowdown. You could test this hypothesis by running

```
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
```

before running your for loop, and see if that slows `register_pipeline.sh` down by about the same amount. 

If this turns out to be the case, finding the number of threads to use with `-itk-threads` to compromise process based parallelism provided by `sct_run_batch` and thread based parallelism used by ITK, would need to be found by experimentation. 

How many cores does your server have? If it has >8 cores, using 5 processes x 1 thread is definitely going to be slow compared to 1 process x 8+ threads, so the comparison may not be fair.

**Comment by leandervaneekelen** [comment]
Setting `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS` to 1 when running my registration pipeline as a for-loop indeed slows it down to a crawl. This was done on Joplin, NeuroPoly's CPU cluster, which has 64 cores, so that supports your hypothesis. 

Do you have advise for a ballpark number of threads to run a `sct_run_batch` call on? I am now testing the same batch call with 8 threads to see how it performs against the non-thread-limited for-loop call.

**Comment by jcohenadad** [comment]
Maybe we should revisit the default value for `-itk-threads` @cfhammill ? Or maybe we don't set it at all, and if it crashes then the error message will be explicit (hopefully) so that users can pay attention to the max thread they should use with their setup...?

**Comment by cfhammill** [comment]
After the SCT developer meeting today we have decided to leave the `-itk-threads` argument default at `1`. We will add further documentation to the argument to point users to this potentially being useful to tweak in the low number of subjects to high number of cores case.

Thanks again for reporting this @leandervaneekelen

**Comment by joshuacwnewton** [comment]
Reopening just until the documentation is updated. 

I can start working on this now. :)
