### ISSUE TITLE
[sct_register_multimodal] : does not produce images in the same physical space

### ISSUE THREAD

**Issue by cepa995** [neuropoly/spinalcordtoolbox#3064]
Hi there! I am new to SCT and so far I am loving it. Although, I do have a question. I am trying to perform symmetric image registration of two images from same subject but different time periods. In other words, I would like to register images into a half-way space if possible.

I was wondering if there is a way to tweak parameters of `sct_register_multimodal `in order to achieve that? Because if I use default `sct_register_multimodal` settings I am getting images that are not in the same physical space. More precisely, its like both images switched their physical space all together. Below are the details:

After registering baseline image with following attributes [**SOURCE**]:
`Image #1: dim = [11, 75, 234];  bb = {[-13.3599 50.891 -73.04], [22.9401 121.203 146.335]};  vox = [3.3, 0.9375, 0.9375];  range = [-38.6614, 1967.17];  orient = Oblique, closest to RPI`

And image taken after 24 weeks with following attributes [**DESTINATION**]:
`Image #1: dim = [11, 75, 271];  bb = {[-15.8444 53.32 -90.6128], [20.4556 123.633 163.45]};  vox = [3.3, 0.9375, 0.9375];  range = [-56.2209, 1509.87];  orient = Oblique, closest to RPI`

Using: `sct_register_multimodal -i img1 -d img2`, I am getting:

- `MR_frame_0001_straight_src_reg.nii.gz `with following attributes:

`Image #1: dim = [11, 75, 271];  bb = {[-15.8444 53.32 -90.6128], [20.4556 123.633 163.45]};  vox = [3.3, 0.9375, 0.9375];  range = [-15.1142, 1703.92];  orient = Oblique, closest to RPI
`
- `MR_frame_0001_straight_dest_reg.nii.gz `with following attributes:

`Image #1: dim = [11, 75, 234];  bb = {[-13.3599 50.891 -73.04], [22.9401 121.203 146.335]};  vox = [3.3, 0.9375, 0.9375];  range = [-17.2532, 1304.43];  orient = Oblique, closest to RPI`

How do I get these images into same half-way physical space? Are there any additional parameters that I would need to adjust in order to do so(i.e. have `bb` of both images the same)?

**Note**: _images information has been generated using_ **ITK-SNAP Converter3D**

**Comment by jcohenadad** [comment]
Hi @cepa995, thank you for reaching out. `sct_register_multimodal` performs a bijective registration, meaning that it gives you the output of img1-->img2 (called img1_reg) and img2-->img1 (called img2_reg).

So in order to have the two images registered together, you need to compare img1_reg with img2, or img1 with img2_reg.

So, for a longitudinal study, you could for example register all your images at t=[1..n] to the image at t=0, and they will all have the same header (incl. the "bb" field).

That being said, if your goal is to register to a "half space", this is something that is currently not implemented in SCT. It would require generating a space in between. But what would be the advantage of that compared to the solution I mentioned above?

**Comment by cepa995** [comment]
Hi @jcohenadad thank you for your comment, this has helped me get better understanding of your tool. And to answer your questions, there would not be any advantages, I agree :). Just curious.
