### ISSUE TITLE
Unsuccessful installation of SCT on GH actions of shimming-toolbox

### ISSUE THREAD

**Issue by maheuss** [neuropoly/spinalcordtoolbox#3112]
### Description

We want to install SCT on the GH actions of the shimming-toolbox in shimming-toolbox/shimming-toolbox#184 but it's unsuccessful for MacOs while it is for Linux. However, the installation steps are exactly the same for both of them.

### Steps to Reproduce

0. Install last release of SCT in `.github/workflows/tests.yml` file of the repository with the following commands:

1. `git clone --depth 1 https://github.com/neuropoly/spinalcordtoolbox`

2. `cd spinalcordtoolbox`

3. `yes | ASK_REPORT_QUESTION=false PIP_PROGRESS_BAR=off ./install_sct` , `yes | ./install_sct` or other commands according to this principle

**Expected behavior:** 
A successful installation on MacOs and Linux

**Actual behavior:** 
The installation is successful for Linux but not for MacOs. Most of the time the error comes from [this step](https://github.com/shimming-toolbox/shimming-toolbox/pull/184/checks?check_run_id=1514698276#step:8:1388) of the installation. This one is cancelled after running for a few hours.
After checking `install_sct`, we are wondering if the error could be from this [line](https://github.com/neuropoly/spinalcordtoolbox/blob/e07cd93cdd9f856b326f81efdd470d10ea642af2/install_sct#L525).

**Comment by joshuacwnewton** [comment]
This seems closely related to #3102. @kousu has refactored SCT's install script to use `-y` as more stable non-interactive mode for exactly this purpose. 

We might want to make sure #3102 fixes this issue before merging it, though. I'll make a comment on the PR. :)

**Comment by kousu** [comment]
This is super bizarre. That CI run (https://github.com/shimming-toolbox/shimming-toolbox/pull/184/checks?check_run_id=1514698276#step:8:1388) is using the exact same line

https://github.com/shimming-toolbox/shimming-toolbox/blob/cb05312a0a5011577b8e64efbe92b81cdf1c1409/.github/workflows/tests.yml#L64

as we have:

https://github.com/neuropoly/spinalcordtoolbox/blob/036dd0009eeb91346d07be43b7a80dd286bf3bdf/.ci.sh#L8

So macOS on Travis: works. macOS on Actions: fails. Bizarre. Actions has a newer macOS than Travis?

**Comment by kousu** [comment]
I'm 90% sure #3102 will fix this though I couldn't explain exactly what the problem is. I just know `yes|` is sketchy.

Also, @jidicula, I appreciate very much that you systematically tested 

* https://github.com/shimming-toolbox/shimming-toolbox/pull/184/commits/4cb81d6ea9392f2c09c91f899c26780210de83c9
* https://github.com/shimming-toolbox/shimming-toolbox/pull/184/commits/64bcad57ed9f7d9802bd418cf63096b6df8733c1
* https://github.com/shimming-toolbox/shimming-toolbox/pull/184/commits/c8417fd8f8f335ad88a8782513212a1b04b46fcd
* https://github.com/shimming-toolbox/shimming-toolbox/pull/184/commits/cb05312a0a5011577b8e64efbe92b81cdf1c1409

I'm sorry none of them helped. I don't know what's wrong. It looks like it's hanging at

https://github.com/neuropoly/spinalcordtoolbox/blob/036dd0009eeb91346d07be43b7a80dd286bf3bdf/install_sct#L528-L529

**Comment by jidicula** [comment]
In any case, looks like we have a successful build on ST: https://github.com/shimming-toolbox/shimming-toolbox/runs/1606848578

**Comment by joshuacwnewton** [comment]
Excellent! I'll reinstate my approval for #3102, then. :)
