### ISSUE TITLE
error: argument -create-seg: expected one argument

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3119]
### Context

When running:
~~~
julien-macbook:~/sct_testing_data/t2 $ sct_label_utils -i t2.nii.gz -create-seg -1,3

--
Spinal Cord Toolbox (git-master-036dd0009eeb91346d07be43b7a80dd286bf3bdf)

sct_label_utils -i t2.nii.gz -create-seg -1,3
--

usage: sct_label_utils -i <file> [-o <file>] [-ilabel <file>]
                       (-add <int> | -create <list> | -create-add <list> | -create-seg <list> | -create-viewer <list> | -cubic-to-point | -disc <file> | -display | -increment | -vert-body <list> | -vert-continuous | -MSE <file> | -remove-reference <file> | -remove-sym <file> | -remove <list> | -keep <list>)
                       [-h] [-msg <str>] [-v <int>] [-qc <folder>] [-qc-dataset <str>] [-qc-subject <str>]
sct_label_utils: error: argument -create-seg: expected one argument
~~~

The error message is caused by the "-1" used as input. Even when inputting the following syntax, the same error occurs:
~~~
sct_label_utils -i t2.nii.gz -create-seg -1,3
~~~

The bug was likely introduced by the recent change from msct_parser to argparse.

**Comment by joshuacwnewton** [comment]
> The error message is caused by the "-1" used as input. Even when inputting the following syntax, the same error occurs:
> 
> ```
> sct_label_utils -i t2.nii.gz -create-seg -1,3
> ```
> 
> The bug was likely introduced by the recent change from msct_parser to argparse.

Definitely this. Argparse is trying to parse `-1,3` as a separate argument called "1,3" instead of parsing it as a value. :sweat_smile: (If you type `-1,3` in isolation, it says `sct_label_utils: error: unrecognized arguments: -1,3`) 

I think the only way to get around this is to use an `=` sign in the call:

```bash
# Adding '=' causes argparse to interpret '-1,3' as an argument value
sct_label_utils -i t2.nii.gz -create-seg=-1,3
```

But, this only works for CLI calls, and wouldn't work for calling `sct_label_utils` via its main function. So, it could be better to change the value we use to specify a midpoint. e.g. instead of `-1` we could use `M` or `mid`. The usage would become:

```bash
sct_label_utils -i t2.nii.gz -create-seg M,3
```

Then, simply update this check: 

https://github.com/neuropoly/spinalcordtoolbox/blob/036dd0009eeb91346d07be43b7a80dd286bf3bdf/spinalcordtoolbox/labels.py#L122-L124

**Comment by joshuacwnewton** [comment]
Ah, shoot. `M`/`mid` wouldn't work as things are right now, because we're parsing the slice indices as integers.

https://github.com/neuropoly/spinalcordtoolbox/blob/036dd0009eeb91346d07be43b7a80dd286bf3bdf/spinalcordtoolbox/scripts/sct_label_utils.py#L95

https://github.com/neuropoly/spinalcordtoolbox/blob/036dd0009eeb91346d07be43b7a80dd286bf3bdf/spinalcordtoolbox/labels.py#L97

We could stop parsing the slice index as ints and validate inputs as strings. e.g.:

```python
        z = str(z)
        if z.lower() is 'm':
            # Select the mid-point in the inferior-superior direction
            z_rpi = int(np.round(out.dim[2] / 2.0))
        elif z.isdigit():
            # Update z based on native image orientation (z should represent superior-inferior axis).
            # Since we don't know which dimension corresponds to the superior-inferior axis, 
            # we put z in all dimensions (we don't care about x and y here).
            coord = Coordinate([int(z), int(z), int(z)])  
            _, _, z_rpi = coord.permute(img, 'RPI')
        else:
            raise ValueError(f"Invalid slice index {z}. Slice must be integer or 'm' (for automatically selecting the midpoint).")    
```

**Comment by jcohenadad** [comment]
> We could stop parsing the slice index as ints and validate inputs as strings inside the function. e.g.:

👍 

Alternatively, since we are about to break retrocompat anyway, we could also introduce this more intuitive flag: `-create-midseg X` (where X is the value of the label)

**Comment by joshuacwnewton** [comment]
> Alternatively, since we are about to break retrocompat anyway, we could also introduce this more intuitive flag: -create-midseg X (where X is the value of the label)

My only question for this is, is it ever the case where a user would want to mix midseg + explicit slice numbers? E.g.

```
sct_label_utils -i t2.nii.gz -create-seg 5,1:14,2:M,3
```

If the two would never be mixed anyway, then I think your suggestion makes a lot of sense.

**Comment by jcohenadad** [comment]
> My only question for this is, is it ever the case where a user would want to mix midseg + explicit slice numbers? E.g.

Great question, the answer is no (in 99.9999999% of the cases). The typical use case is when an MR technician centers the field of view of an MRI metric (e.g. DWI, MT, etc.) at a specific location (e.g. C2-C3 disc). In this case we can do a single-disc-based registration to template (not accounting for the location of the other discs)

**Comment by joshuacwnewton** [comment]
Whoops, sorry for the delay. This got lost in my inbox -- I'll start this ASAP.
