### ISSUE TITLE
Replace `pylint` call in `.ci.sh` with a more useful linting check

### ISSUE THREAD

**Issue by kousu** [neuropoly/spinalcordtoolbox#3142]
We have pylint running on every CI job:

https://github.com/neuropoly/spinalcordtoolbox/blob/6172cd22feeb0f64ac1bd68bce3f89f7109e68b8/.ci.sh#L26-L28

but there never seems to be any output from it. e.g. there's https://travis-ci.com/github/neuropoly/spinalcordtoolbox/jobs/466281661#L3994

> Collecting pylint
>  Downloading pylint-2.6.0-py3-none-any.whl (325 kB)

but I've never seen code fail the linting step. Is this actually doing anything?

**Comment by kousu** [comment]
@joshuacwnewton prompted this.

**Comment by joshuacwnewton** [comment]
`pylint` does indeed run. But, the presence of `--errors-only` hides a number of [message types](https://docs.pylint.org/en/1.6.0/output.html#source-code-analysis-section), hence the empty output. Removing `--errors-only` shows a _ton_ of warnings that have silently gone unnoticed. ([`pylint-log.txt`](https://github.com/neuropoly/spinalcordtoolbox/files/5756194/pylint-log.txt)) 

Checking for these warnings/style tips is the main point of `pylint`! Without them, I don't think this `pylint` call is very useful to us. In fact, I'm not sure this call is even worth keeping if kept as-is, unless we improve it in some way.

_(Historical context: The call was added in 2018 as part of https://github.com/neuropoly/spinalcordtoolbox/commit/cbcbc83b596b89ec505470c97eb7edfb5ddb578e.)_

**Comment by joshuacwnewton** [comment]
Because of the sheer number of warnings, it would be quite a large undertaking to eliminate them all, so I don't think we can rely on simply calling `pylint` as a required check. Instead, I think it would be more useful to try to lint PR diffs. (That is, focus on preventing new issues introduced by the changes in PRs.)

Some ideas:

* Manually run `flake8 --diff`, comparing `master` to the PR commit, which is [what `scikit-learn` does](https://github.com/scikit-learn/scikit-learn/blob/6b4f82433dc2f219dbff7fe8fa42c10b72379be6/build_tools/circle/linting.sh#L126-L135).
* Use one of the available GitHub Actions for running various linters on PRs (e.g. [`python-lint`](https://github.com/marketplace/actions/python-code-quality-and-lint), [`flake8-your-pr`](https://github.com/marketplace/actions/run-flake8-on-your-pr-with-annotations), [`Lintly-flake8`](https://github.com/marketplace/actions/lintly-flake8))

**Comment by kousu** [comment]
We should definitely get it out of `.ci.sh`; or at least make it an optional section.

`flake8 --diff` is an interesting idea! I take it that means it would only catch *newly introduced* problems? That could be good. But it also means that if someone gets something past it we'll forget about the issue until someone runs `pylint` or `flake8` manually again.

**Comment by joshuacwnewton** [comment]
> But it also means that if someone gets something past it we'll forget about the issue until someone runs pylint or flake8 manually again.

True. But, at the same time, it would mean our warnings would go from, say, ~70,000 to 70,001... we're sort of past the point of addressing each and every issue. I'm thinking of this more as a "stem the bleeding" measure than tackling this head-on. :sweat_smile:

**Comment by kousu** [comment]
:sweat_smile:

**Comment by kousu** [comment]
And of course, our `pylint` doesn't even work with `SCT_INSTALL_TYPE=package`: https://github.com/neuropoly/spinalcordtoolbox/runs/1629734147?check_suite_focus=true#step:5:1817 (tangential to #3140)

**Comment by kousu** [comment]
Duplicate of  #1538  ?

**Comment by joshuacwnewton** [comment]
Good catch. I mentioned the new info from here in that issue. Closing this one. :slightly_smiling_face:
