### ISSUE TITLE
simplify usage

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#323]
remove flag:
~~~~
  -p {binary_centerline,text_file}Type of output wanted: 
                                binary_centerline: return binary NIFTI file of the centerline 
                                text_file: return text file with float coordinates according to z
~~~~

let's just output both things without asking.

**Comment by jcohenadad** [comment]
Tanguy, could you also simplify:
~~~~
sct_get_centerline_from_labels -i <[[','], 'file']>
~~~~
to this:
~~~~
sct_get_centerline_from_labels -i labels1.nii,labels2.nii,labels3.nii
~~~~
thx!

**Comment by tanguymagnan** [comment]
We have changed the parser so that the usage become more transparent

Here is the result for sct_get_centerline_from_labels (with also a change
of the example):

USAGE

sct_get_centerline_from_labels -i <list of: file>



MANDATORY ARGUMENTS

  -i <list of: file>          List containing segmentation NIFTI file and
label NIFTI files. They

                              must be 3D. Names must be separated by commas
without spaces.



OPTIONAL ARGUMENTS

  -o <file_output>            Name of the output NIFTI image with the
centerline and of the output

                              text file with the coordinates (z, x, y) (but
text file will have

                              '.txt' extension). Default value =
generated_centerline.nii.gz

  -r {0,1}                    Remove temporary files. Specify 0 to get
access to temporary files.

                              Default value = 1

  -v {0,1,2}                  Verbose. 0: nothing. 1: basic. 2: extended.
Default value = 0



EXAMPLE

sct_get_centerline_from_labels -i
data_seg.nii.gz,label1.nii.gz,label2.nii.gz -r 0 -v 0



Is it good enough?

2015-04-20 13:02 GMT-04:00 Julien Cohen-Adad <notifications@github.com>:

> Tanguy, could you also simplify:
>
> sct_get_centerline_from_labels -i <[[','], 'file']>
>
> to this:
>
> sct_get_centerline_from_labels -i labels1.nii,labels2.nii,labels3.nii
>
> thx!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neuropoly/spinalcordtoolbox/issues/323#issuecomment-94509940>
> .
>



-- 
Tanguy Magnan de Bornier
Second year student at the Ecole Centrale de Lille, France.
Ph.: 06.77.25.29.91
