### ISSUE TITLE
All TravisCI builds stalled because our free plan is out of credits

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#3273]
The only reason we have been able to use Travis for the past several months is due to a glitch: We never signed up for the free plan via Travis.com's interface, so our organization was in a bugged state, letting us run jobs without using credits. But, now we _are_ on the free plan. As it turns out, Neuropoly's usage is enough to deplete 10000 credits in a single day:

<details>
<summary> Large image </summary>

![image](https://user-images.githubusercontent.com/16181459/110814142-2d608d00-8257-11eb-88b2-ff2b9c91947f.png)

</details>

We should expedite the migration to GitHub Actions (#3125), and possibly upgrade our TravisCI plan temporarily in the meanwhile, depending on how urgently we need CI for PRs besides #3125.

**Comment by dyt811** [comment]
Adding link to issue history and record from yesterday. https://docs.google.com/document/d/1ZcgynzX-XQevp6EQj-IgWBH0fSFNzHMd84xfUEuxCn8/edit?usp=sharing

**Comment by joshuacwnewton** [comment]
We've purchased a plan for Neuropoly, yet our build requests are still stalling: https://travis-ci.com/github/neuropoly/spinalcordtoolbox/requests. @dyt811 is looking into this with Travis support. 

As a heads-up, since we have TravisCI as a "Required Check", this will eventually prevent #3215 from being merged.

**Comment by dyt811** [comment]
Additional credits have been purchase now (25K). Because apparently MacOS build require credits whether you are on plan or not (Free plan also doesn't even allow credit purchase) per fine below and if no credits available, it will block all the ENTIRE build path (i.e. even non-mac path like Ubuntu/Windows/Linux), not just the mac build path. 

![image](https://user-images.githubusercontent.com/6720068/110860705-1b004680-828b-11eb-9e1c-ad31f8a773ee.png)

![image](https://user-images.githubusercontent.com/6720068/110860630-04f28600-828b-11eb-857b-9d6f84953fa2.png)

Please give it a try again and keep me posted.

**Comment by joshuacwnewton** [comment]
I've triggered a new build for #3125, and [it's working](https://github.com/neuropoly/spinalcordtoolbox/pull/3125/checks?check_run_id=2090411150). Thanks much! 

Considering that SCT used ~10k credits in one day during typical usage, I worry with 25k credits we'll run out again soon. So, we could disable Travis immediately as part of #3125, which would leave more credits for ADS.

**Comment by dyt811** [comment]
Yeah, the free 10K credit was used because it was the cumulation of all build paths (Win/Ubuntu/Ma etc) so depleted quickly overnight. The new 25K will only be required for Mac and all other OS build time will not require credit (now that we are on a concurrency plan). I added a weekly reminder in slack to monitor this issue more closely.

**Comment by joshuacwnewton** [comment]
> Yeah, the free 10K credit was used because it was the cumulation of all build paths (Win/Ubuntu/Ma etc) so depleted quickly overnight. The new 25K will only be required for Mac and all other OS build time will not require credit (now that we are on a concurrency plan). I added a weekly reminder in slack to monitor this issue more closely.

This makes sense! Thanks for the clarification, and for your work to quickly address this.

I'm going to close this issue for now, then, as the remaining work for SCT is covered by issue #3071.
