### ISSUE TITLE
Image.change_orientation() removes the field absolutepath of an image

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3304]
### Description

Image.change_orientation() removes the field absolutepath of an image.

### Steps to Reproduce

SCT version: e7cfb597c24e32805ea974fac2ab264876cdfff2

dummy code:
```python
img = Image.('image')
img.absolutepath
> awesomepath
img.change_orientation('LPI')
img.absolutepath
> # Nothing is output! 
```

**Comment by Drulex** [comment]
Took a look at the method and noticed that there is a keyword argument `generate_path` that modifies the path with an orientation-specific suffix when set to `True` (default value is `False`).

https://github.com/neuropoly/spinalcordtoolbox/blob/4fd149d7d381c834e79dfdf8c0116b97aaef2fb7/spinalcordtoolbox/image.py#L437-L460

I'm assuming that the reasoning is the following: If we change an image's orientation we don't necessarily want to maintain the `absolutepath`, because it may not make sense. The function provides the ability to "intelligently" modify the path via `generate_path`, otherwise it is voided and the responsibility is on the caller to provide the correct path (when saving for instance).

In my opinion this makes sense. It is safe, because without an `absolutepath` the caller can not save the image and risk accidentally overwriting it.

```python
>>> a = Image("/work/exmakhina/neuropoly/spinalcordtoolbox/sct_testing_data/t2/t2.nii.gz")
>>> a.change_orientation('RPI')
<spinalcordtoolbox.image.Image object at 0x7f7428821080>
>>> a.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/exmakhina/neuropoly/spinalcordtoolbox/spinalcordtoolbox/image.py", line 507, in save
    raise RuntimeError("Don't know where to save the image (no absolutepath or path parameter)")
```
What do you think @jcohenadad ?

**Comment by jcohenadad** [comment]
hum... there is probably a _very_ good reason why we came up with this in the past, but in the past, things were also differently handled. 

To me, this method is a manipulation on an image, similarly to other methods that are in the Image class (eg: `copy_qform_from_ref()`, `set_sform_to_qform()`). So, from a coding perspective, I find it much more intuitive to leave the responsibility to the caller to make sure the file name should be changed upon saving the image. E.g., my way of doing things would be:

1. `img = Image.load(FNAME_IMAGE)`
2. `img_new = img.copy()`
3. `img_new.SOME_MANIPULATION`
4. `img_new.save(FNAME_NEW)`

The advantage being that we can use the existing field. E.g.:

4. `img_new.save(ADD_SUFFIX(img_new.absolutepath, '_new'))`

What do you think?

Note: going through the code I also realized that this concerns other methods:

https://github.com/neuropoly/spinalcordtoolbox/blob/4fd149d7d381c834e79dfdf8c0116b97aaef2fb7/spinalcordtoolbox/image.py#L413

https://github.com/neuropoly/spinalcordtoolbox/blob/4fd149d7d381c834e79dfdf8c0116b97aaef2fb7/spinalcordtoolbox/image.py#L462

**Comment by Drulex** [comment]
I agree. Just to clarify: with the current approach we can still do everything that you pointed out. The only difference is that if we **don't** void the `absolutepath` in the manipulation method and then go on to save the image without specifying a new path it will overwrite the original image without complaining.

I think the cleanest way would be to refactor the manipulations method that do more than manipulating (for example changing paths via `generate_path` and move the path modification to the caller.

**Comment by joshuacwnewton** [comment]
In #3320, there are a few spots where this issue had to be worked around: https://github.com/neuropoly/spinalcordtoolbox/pull/3320#discussion_r611218125, https://github.com/neuropoly/spinalcordtoolbox/pull/3320#discussion_r611218650
