### ISSUE TITLE
Discrepancy between `fslhd` and `sct_image -getorient`

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#3311]
### Description

fslhd gives LPI while sct_image -getorient gives RPI.

### Steps to Reproduce

```console
git clone https://github.com/sct-data/exvivo-template.git
cd exvivo-template
git checkout 6a595f97410f4a26882852fb6d1ab40389b78206
cd template
```

With sct_image:
```console
sct_image -i exvivo_t2.nii.gz -getorient
RPI
```

with fslhd:
```console
fslhd exvivo_t2.nii.gz
[...]
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
```

Related to https://github.com/sct-data/exvivo-template/issues/16

**Comment by joshuacwnewton** [comment]
I am currently working on #504. Since displaying the header will include this information, we could just deprecate `-getorient` as part of that effort?

**Comment by joshuacwnewton** [comment]
I've looked into this behavior, and it turns out this is due to a new bug introduced in #2858.

https://github.com/neuropoly/spinalcordtoolbox/blob/c09a14a2e12317edebda03cad01c8aa4cf64aa31/spinalcordtoolbox/scripts/sct_image.py#L193-L194

The default value for `arguments.set_sform_to_qform` is actually `False`, and _not_ `None`, so right now this always fires. :scream:

The reason this affects orientation is because calling `arguments.set_sform_to_qform` causes `im.hdr.get_best_affine()` to return the wrong affine, and hence the wrong orientation:

```python
# Before `self.hdr._structarr['sform_code'] = self.hdr._structarr['qform_code']`
> im.hdr.get_best_affine()
[[0.08 0.   0.   0.  ]
 [0.   0.08 0.   0.  ]
 [0.   0.   0.08 0.  ]
 [0.   0.   0.   1.  ]]
> res = "".join(nib.orientations.aff2axcodes(im.hdr.get_best_affine()))
'RAS'
> orientation_string_nib2sct(res)
'LPI'

# After `self.hdr._structarr['sform_code'] = self.hdr._structarr['qform_code']`
> im.hdr.get_best_affine()
[[ -0.08         0.           0.           9.95999978]
 [  0.           0.08         0.          -9.95999978]
 [  0.           0.           0.08       -39.55999912]
 [  0.           0.           0.           1.        ]]
> res = "".join(nib.orientations.aff2axcodes(im.hdr.get_best_affine()))
'LAS'
> orientation_string_nib2sct(res)
'RPI'
```

I'll open up a PR to fix this ASAP. 

_(Also, as an aside, it's error-prone to have both `None` and `False` as default values in `sct_image`, so I'll see if something can be done about that.)_

**Comment by jcohenadad** [comment]
wow!!! good catch @joshuacwnewton 👏   thank you!!!
