### ISSUE TITLE
funky segmentation

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#366]
also related to: https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/d3624a4a/?limit=25

data:
sct_issue/20150515_emil/data

~~~~
sct_propseg -i t1w_01.nii -t t1 -init-centerline t1w_01-initcenterline.nii.gz 
~~~~
![screen shot 2015-05-15 at 18 41 31](https://cloud.githubusercontent.com/assets/2482071/7663033/24b91904-fb32-11e4-97c6-eedf11503019.png)

**Comment by benjamindeleener** [comment]
The issue comes from a wrong orientation of the image (as it can be seen on FSLview). The orientation of the image in the header file is RPI while the actual orientation of the image is AIL.
Therefore, the spline approximation of PropSeg don't work because it assumes a correct orientation of the image:
First, the orders the points provided by the user based on the axis of the inferior-superior direction. Then it fits a b-spline that goes through the ordered points so if the orientation is not correct, the points are not correctly ordered and the spline will not follow correctly the points. That is what happen and can be seen in the image.

Solution: reorient the image.

I developed a new tool in sct_orientation to fix the orientation error (option -a):
````
sct_orientation -i t1w_01.nii -a AIR -o t1w_01_corrected.nii
````

Segmentation results are good once this is fixed:
```
sct_propseg -i t1w_01_corrected.nii -t t1 -up 200
```
![fixed](https://cloud.githubusercontent.com/assets/7757117/7667058/da17565c-fbc9-11e4-8553-3507a7de3985.png)
