### ISSUE TITLE
duplication bug due to wrong cropping of the template (or the warping field)

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#367]
Data: sct_issue/20150518_carmine

A bug of image duplication, due to a incorrect cropping of the template, occurs in the brainstem when registering the template on an anatomical image.

![registration](https://cloud.githubusercontent.com/assets/7757117/7681025/314ce52e-fd3a-11e4-915f-f7543d941b99.gif)

**Comment by jcohenadad** [comment]
This is due to the fact that the input data are 0.5x0.5x0.3mm, therefore when creating the crosses in straighten_spinalcord, the output warping field is too narrow, because the cross is defined in voxel space without taking into account voxel size.

Working on a fix, which resamples data to 1mm iso at the beginning of register_to_template  (branch: jca_reg2template1mm)
