### ISSUE TITLE
first cross is not orthogonal to the cord

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#370]
data: 
~~~~
sct_example_data/t2
~~~~

syntax:
~~~~
sct_straighten_spinalcord -i t2.nii.gz -c t2_seg.nii.gz -v 2
~~~~

check derivatives-- likely related to the problem.

![screen shot 2015-05-20 at 13 48 47](https://cloud.githubusercontent.com/assets/2482071/7732629/390907fc-fef7-11e4-9ac3-4442afef3dc3.png)

Result:
![screen shot 2015-05-20 at 13 53 09](https://cloud.githubusercontent.com/assets/2482071/7732696/b007a8ea-fef7-11e4-852a-395e7dbf06e3.png)

**Comment by benjamindeleener** [comment]
This problem does not appear when using nurbs smoothing:

````
sct_straighten_spinalcord -i t2.nii.gz -c t2_seg.nii.gz -v 2 -a nurbs
````

![straighten_nurbs](https://cloud.githubusercontent.com/assets/7757117/7732800/5b46a314-fef8-11e4-81f0-a223b7c035f4.png)

**Comment by jcohenadad** [comment]
created branch: issue_370

**Comment by benjamindeleener** [comment]
The issue was fixed by using the 'valid' option during convolution with numpy in order to avoid edge's effects.

Results:
![crosses_good](https://cloud.githubusercontent.com/assets/7757117/7734178/392e2770-ff02-11e4-860f-6d4daa791ef6.png)
The result on the straightening is not so good, despite a correct smoothing of the centerline and correct crosses...
![straightening_notsogood](https://cloud.githubusercontent.com/assets/7757117/7734203/66af3e6e-ff02-11e4-8890-4a550dcc2eed.png)

**Comment by benjamindeleener** [comment]
The issue related above is completely related to the parameters of isct_ANTSUseLandmarkImagesToGetBSplineDisplacementField. Above, I was using the following parameters:

```
isct_ANTSUseLandmarkImagesToGetBSplineDisplacementField tmp.landmarks_curved_rigid.nii.gz tmp.landmarks_straight.nii.gz tmp.warp_straight2curve.nii.gz 5x5x10 3 3 0
```

Now, I am using these parameters:
```
isct_ANTSUseLandmarkImagesToGetBSplineDisplacementField tmp.landmarks_curved_rigid.nii.gz tmp.landmarks_straight.nii.gz tmp.warp_straight2curve.nii.gz 5x5x10 3 2 0
```
![straightening_good](https://cloud.githubusercontent.com/assets/7757117/7734365/7ff62436-ff03-11e4-8fb5-568dead68c3a.png)

That means that we need to find the good parameters for the straightening for a large dataset (issue #364 & issue #371

This issue has been fixed in commit b0f49194271034218029723c5a7d99ccc317f61d in branch issue_370. Will soon be merged on master.

**Comment by jcohenadad** [comment]
has it been merged to master?  if so please close issue and delete branch

**Comment by benjamindeleener** [comment]
Done.
