### ISSUE TITLE
sct_straighten_spinalcord is very sensitive to the parameters of isct_ANTSUseLandmarkImagesToGetBSplineDisplacementField

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#371]
see issue #370

**Comment by jcohenadad** [comment]
here is another example:

data:
~~~~
sct_issue/20150525_virginie/data
~~~~

syntax:
~~~~
sct_straighten_spinalcord -i t2.nii.gz -c t2_seg.nii.gz -r 0 -v 2
~~~~

Result:
![screen shot 2015-05-25 at 13 57 52](https://cloud.githubusercontent.com/assets/2482071/7800628/3eb966e0-02e6-11e5-988a-78e3856151c5.png)

The problem really seems to come from the lack of centerline guides for estimating warping field, as shown here:
![screen shot 2015-05-25 at 13 56 00](https://cloud.githubusercontent.com/assets/2482071/7800622/3ba8d666-02e6-11e5-85a7-e86b9f497ccc.png)

**Comment by jcohenadad** [comment]
Here are the results when a gapz=7 (instead of gapz=15) is used:

![screen shot 2015-05-25 at 14 02 29](https://cloud.githubusercontent.com/assets/2482071/7800667/d6ec8b72-02e6-11e5-9f81-fcc61e026fac.png)

![screen shot 2015-05-25 at 14 01 53](https://cloud.githubusercontent.com/assets/2482071/7800668/dbc23804-02e6-11e5-9b70-39fccc7ff1ce.png)

**Comment by jcohenadad** [comment]
Issue will be addressed by recoding the function to work in parametric space.

**Comment by jcohenadad** [comment]
N.B. Accuracy of straightening (MSE) is not a good measure of quality (see two examples above)

**Comment by benjamindeleener** [comment]
This issue has been addressed and is not fixed by the use of labels along the spinal cord and continuous indexes.

MSE and maximum distance computation has also been improved.
