### ISSUE TITLE
remove or merge sct_crop_over_mask into sct_crop_image

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#541]

**Comment by SaraDupont** [comment]
Done on branch sd_issue541_crop/
- with sct_crop_image if both the -m (mask) and -b (background) flags are used : 
  - the shape of the images isn't changed 
  - the croping area correspond exactly to the mask : eg if the mask is a spinal cord segmentation (ellipse shaped tube) the crop image will be an image containing ONLY the spinal cord, with the background value around instead of an image containing a rectangle area including the cord. (see examples below) 
![mask_background](https://cloud.githubusercontent.com/assets/5857909/10282497/41415ca8-6b49-11e5-83e3-9fe4c19ea23e.gif)

- the other option availbale in sct_crop_over_mask is now a function of msct_image : crop_and_straighten (The users won't need it : it's a specific case). It crops an image around a square mask, the output image are the crop slices all aligned on the center of the square mask.

**Comment by jcohenadad** [comment]
i'm not sure about the utility of "sct_crop_image -m (mask) -b background", given that the same thing could be done with:
~~~
sct_maths -i image -mul mask
~~~
the only difference is that the background cannot be set to a specific value, but is that something that could be useful to someone?

**Comment by SaraDupont** [comment]
The background with a specific value is not necessarily very usefull. I just thought it was more logical to do that when a background is specified with a mask, and maybe it's more intuitive for the user to use sct_crop_image than sct_maths -mul when they want to crop.  But I can change that if you think it's easier to use sct_maths -mul.

**Comment by jcohenadad** [comment]
no that's fine let's just leave it.
thanks!
