### ISSUE TITLE
move to dev, and update batch_processing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#546]

**Comment by SaraDupont** [comment]
Done ! The result is not perfect but really nice. If it's OK for you we can close this.
In blue: automatic GM segmentation, in Red-Yellow: template GM registered on mt1
![reg_slice1](https://cloud.githubusercontent.com/assets/5857909/10233494/a7acce90-685c-11e5-9e08-5827f3650840.gif)

**Comment by jcohenadad** [comment]
nice!  so, did you update the batch_processing accordingly? (i started to modify it but it was incomplete). Also, did you see the info on issue #536?

Another thing to investigate is the scaling of the probabilistic map. We need to make sure that the registered WM + GM equals 1 in the spinal cord (it should). Maybe play with interpolation methods.

**Comment by SaraDupont** [comment]
Yes I did (modify the batch_processing and see the info) 
I just check : the sum of the registered WM + GM gives 1 in the SC.  Sometimes the visualization is a bit tricky because the threshold on the color map exclude the value 0.5 on both WM and GM so if a voxel is exactly at 0.5 you don't see it but the sum is correct.

**Comment by SaraDupont** [comment]
I also changed the doc on sourceforge for sct_register_graymatter : 
https://sourceforge.net/p/spinalcordtoolbox/wiki/register_to_metric/
and added a section tips & tricks to the list of tools : we could add other information about registration  on that section (like what to do when register multimodal fails).

**Comment by jcohenadad** [comment]
awesome :+1:
