### ISSUE TITLE
Problem with landmark creation 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#581]
branch master

data: **sct_issues/20151014_issue_581**

when applying warping field to landmarks, I get the following result:
![screen shot 2015-10-14 at 10 02 17](https://cloud.githubusercontent.com/assets/2482071/10486254/1c14cc02-725c-11e5-89dd-d0fffc09466f.png)

I looked at the code to make sure that real labels are used (instead of image labels), and I found that at line 891, the function ``isct_ANTSLandmarksBSplineTransform`` is used instead of ``isct_ANTSUseLandmarkImagesWithTextFileToGetBSplineDisplacementField``, although text file is input in the function (my intuitive understanding is that the later function inputs text file, while the first does not-- otherwise names should be made more intuitive).

Moreover, there is no symmetry in the code. Curve2straight shows an "error you should never get to this point (l904), while straigh2curve uses: "isct_ANTSUseLandmarkImagesToGetBSplineDisplacementField".

**Comment by jcohenadad** [comment]
Additional info below:
![screen shot 2015-10-14 at 12 25 05](https://cloud.githubusercontent.com/assets/2482071/10490400/d99a2ff8-726e-11e5-8898-4f208cd04058.png)

Potential issues are:
- gap not consistent between curved and straight
- values are float in straight and int in curved
- 557 does not correspond to 558 (both views are sagittal) --> but this might be related to the new orientation of straight?

**Comment by benjamindeleener** [comment]
The issue came from the computation of gaps between each cross. We decided to resample the input image of to 1mm isotropic so that the issue does not appear anymore.
We also removed the resampling into sct_register_to_template.

Unfortunately, this causes an offset in z during the registration to the template.

**Comment by jcohenadad** [comment]
can the issue be caused by a problem in the resampling? (e.g., wrong center)

**Comment by benjamindeleener** [comment]
Not sure. It is probably caused by an issue in the computation of the transformation between straight landmarks and template landmarks.

**Comment by benjamindeleener** [comment]
That was it. I remove the computation of the translation + z-scaling and replaced it with an affine transformation from ```isct_ANTSUseLandmarkImagesToGetAffineTransform``` and it works great.
However, I showed before that the latter method was less accurate than the first one (despite some bugs). So I improved the generation of the crosses into the input image space, so that they are perpendicular to the spinal cord and with much more points (double square crosses like in the straightening process). The affine transform proposed by ```isct_ANTSUseLandmarkImagesToGetAffineTransform``` is nearly a translation + z-scaling with this approach.

**Comment by jcohenadad** [comment]
beer well deserved! :+1:

**Comment by jcohenadad** [comment]
remove binary

**Comment by benjamindeleener** [comment]
To do:
- [ ] remove binary ``isct_ANTSUseLandmarkImagesToGetAffineTransform`` from bin/ folder
- [ ] change resampling of segmentation to trilinear

**Comment by benjamindeleener** [comment]
Binaries were removed in commit a97c07d
