### ISSUE TITLE
create gif for checking output

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#588]

**Comment by SaraDupont** [comment]
Output mid axial plan with gray matter segmentation when flag -qc is used.

I created function ```save_plan()``` in ```msct_image``` which is a generalization of ```saveSagittalPlan()```. Several param can be specified : 
  - plan: sagittal, coronal, or axial (default = 'sagittal')
  - index: index of the slice to save, if not specified, the middle slice is saved
  - format: default = '.png'
  - suffix: suffix to add to the saved image file name
  - seg: segmentation image (type Image) to add in  transparency to the image to save. 
  - thr: threshold to apply to the segmentation

**Comment by jcohenadad** [comment]
fantastic! could you please just change "plan" for "plane"
thanks!

**Comment by SaraDupont** [comment]
Since gif output with matplotlib seems to need an external package (to write gif), for now, I did a function ```save_multiple_slices()``` with basically the same parameters as ```save_plane()``` that saves two png (or other) images with the specified number of slices: one with "raw" slices, one with the specified segmentation (if there is one) added in transparency to each slice.  
Available colormaps: 
- red
- red-yellow
- blue-cyan

Used in sct_segment_graymatter (5 slices with GM segmentation) and sct_warp_template (4 slices with warped WM from temlpate)

Output in sct_segment_graymatter: 
- with seg:
![t2star_axial_plane_seg](https://cloud.githubusercontent.com/assets/5857909/10924005/044250b2-8252-11e5-9b03-0958500f55e4.png)
- raw:
![t2star_axial_plane](https://cloud.githubusercontent.com/assets/5857909/10924006/04485fd4-8252-11e5-9562-1970b06895c4.png)
