### ISSUE TITLE
sct_register_multimodal should enable non-RPI orientation

### ISSUE THREAD

**Issue by benjamindeleener** [neuropoly/spinalcordtoolbox#634]
Check if destination data is RPI...

ERROR: diff_FAr.nii.gz is not in RPI orientation. Use sct_image -setorient to reorient your data. Exit program.

**Comment by tanguyduval** [comment]
Currently this problem can have bad consequences for the user:
The user has to put in RPI both the destination image (-d) and the segmentation (-dseg). If only the destination is in RPI, sct_register_multimodal outputs no error.. but registration is badly estimated!!

Two solutions:
1- Best solution is to put in RPI in the code both the destination and the seg
2- Tell the user to put also -dseg in RPI....

**Comment by SaraDupont** [comment]
@tanguyduval I can't reproduce this issue, is it still happening ?  
From my point of view, we shouldn't put the destination image in RPI, it should stay in its original orientation. However, the destination image an segmentation should be in the same orientation (actually in the same space, which includes he orientation) --> is that the problem here ? If so, we can add a check to assert that the image and segmentation are in the same orientation.

**Comment by jcohenadad** [comment]
i think the segmentation does **not** need to be in the same voxel space as the image (only in the same physical space).
please check if this is the case, before adding a check that asserts if seg and image are in the same voxel space

**Comment by tanguyduval** [comment]
I don't know sorry.. I should have put example dataset to test this issue..

**Comment by jcohenadad** [comment]
however i agree that the requirement to have destination image in RPI is annoying for the user. Automatic reorientation could indeed be added to the code.

**Comment by SaraDupont** [comment]
Th reorientation of the destination image is already implemented in the code : 
- orient in RPI at the beginning: 
-->in `sct_register_multimodal`, line 393: 
`    sct.run('sct_image -i dest.nii -setorient RPI -o dest_RPI.nii')`
- reorient in original orientation at the end by concatenating the transformations directly to `dest.nii` space (instead of `dest_RPI.nii`) : 
-->in `sct_register_multimodal`, line 461:
`    sct.run('sct_concat_transfo -w '+','.join(warp_forward)+' -d dest.nii -o warp_src2dest.nii.gz', verbose)
`
