### ISSUE TITLE
[EASY TO SOLVE] [sct_concat_transfo] output filename '.nii' creates wrong warping fields.. '.nii.gz' gives good ones

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#728]
data in

```

/Volumes/folder_shared/BUGS/sct_concat_transfo/bugGZ
```

Wrong procedure:

```
sct_concat_transfo -d dest_RPI.nii -w step0/step00GenericAffine.mat,step0/step01Warp.nii.gz,warp_src_reslice2dest.nii.gz -o warptest.nii
sct_apply_transfo -i src.nii -d dest.nii -w warptest.nii
```

Good Procedure:

```
sct_concat_transfo -d dest_RPI.nii -w step0/step00GenericAffine.mat,step0/step01Warp.nii.gz,warp_src_reslice2dest.nii.gz -o warptest.nii.gz
sct_apply_transfo -i src.nii -d dest.nii -w warptest.nii.gz
```

NEW BUG.. Was working with previous version of SCT

**Comment by benjamindeleener** [comment]
If this is an issue of .nii/.nii.gz, it could be a problem in NiBabel, which is not easy to solve. I'm on it.

**Comment by benjamindeleener** [comment]
This issue seems to be caused by a wrong conversion of a file, from ```.nii.gz``` to ```.nii``` in NiBabel. Indeed, saving the final file into ```sct_concat_transfo``` is done using ```sct_utils.generate_output_file```
```
sct.generate_output_file('warp_final.nii.gz', path_out+file_out+ext_out)
```

In this script, the file is converted from ```.nii.gz``` to ```.nii```, using the function ```convert``` from ```sct_convert``` and this script uses the function ```changeType()``` of class ```Image```. Basically, the latter function only read and write the image, therefore changing the extension of the image.

Question: does nibabel really decompress the image when converting from ```.nii.gz``` to ```.nii```?

**Comment by benjamindeleener** [comment]
Temporary solution: using gunzip to decompress the file instead of using nibabel.

At line 416 of ```sct_utils.py```:
```python
if ext_in != ext_out:
    # Generate output file
    if ext_in == '.nii.gz' and ext_out == '.nii':  # added to resolve issue #728
        run('gunzip -f ' + fname_in)
        os.rename(path_in + file_in + '.nii', fname_out)
    else:
        from sct_convert import convert
        convert(fname_in, fname_out)
```

**Comment by tanguyduval** [comment]
told you it was easy :-)

2016-03-02 17:13 GMT-05:00 Benjamin De Leener <notifications@github.com>:

**Comment by SaraDupont** [comment]
The use of gunzip in ```sct_utils``` creates another issue when implementing a better ```concat_data()``` in ```sct_image```  (No idea why this interfere with the way too deal with .nii files though) : the tests of sct_label_vertebrae and sct_smooth_spinalcord never stops

Try to un comment lines 420 to 425 of ```sct_utils``` and test sct_label_vertebrae and sct_smooth_spinalcord  to see if the bug persist on an other station (I'm on evans).

**Comment by benjamindeleener** [comment]
@tanguyduval the issue was finally easy to solve ;-)

The issue comes from the fact that NiBabel corrupts warping field when converting them from `.nii`and `.nii.gz` or inversely (when using `sct_convert`).

The way to solve it is to avoid this conversion by producing the right extension (either `.nii` or `.nii.gz`) directly by `isct_ComposeMultiTransform`.

It has been done in commit c9d2496f3b4a02f2dab7a73c89927afcfbe62b2f
