### ISSUE TITLE
add flag -o to output values in txt file (like in sct_extract_metric)

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#812]

**Comment by slevyrosetti** [comment]
I will add a flag -o to enable the user to choose the path and name of the output files. Since there are 3 different output files (csa per slice, csa mean between the selected slices/vertebral levels, volume), I will use the specified output name as a prefix and add _csa.txt, _csa_mean.txt and _volume.txt for the 3 output file. Is that okay?

**Comment by jcohenadad** [comment]
yes that's fine. But please mention in the flag description that this is a prefix, not a file name. And give an example. Thanks!

**Comment by slevyrosetti** [comment]
If the user choose to extract the centerline from a segmentation using sct_process_segmentation, the output file is named <input_filename>_centerline.nii.gz. Do you want me to enable the user to choose this output filename with the flag -o? Or do you want the flag -o to only concern the output files of CSA estimation?

**Comment by jcohenadad** [comment]
for now, let's just deal with -csa flag

**Comment by slevyrosetti** [comment]
All right!

**Comment by slevyrosetti** [comment]
Fixed in commits e0a7123 and 61672e8
